### ISSUE TITLE
C provider

### ISSUE THREAD

**Issue by Milo123459** [railwayapp/nixpacks#101]

**Comment by nebulatgs** [comment]
I think we should split this into a GCC and Clang provider

**Comment by coffee-cup** [comment]
Do you have any real world example apps that are built with just C? Feels like this provider would rarely be used

**Comment by Milo123459** [comment]
Bad idea, I think it should just be an all generic "C" provider.

**Comment by Milo123459** [comment]
> Do you have any real world example apps that are built with just C? Feels like this provider would rarely be used

Compiled code from languages like vlang, basically.

**Comment by coffee-cup** [comment]
In that case a vlang provider would be more useful?

**Comment by Milo123459** [comment]
Yeah, I agree. Still, it'd be good to just have.

**Comment by nebulatgs** [comment]
would be much more useful to have a C++ provider that also supports C, rather than separating those.
many C++ programs use C libraries (think OpenGL)

**Comment by Milo123459** [comment]
We could have a C++ provider as well. I'll make another issue.
