### ISSUE TITLE
Support specific node versions instead of just majors

### ISSUE THREAD

**Issue by flybayer** [railwayapp/nixpacks#1017]
### Feature request

This is a recurring frustration for our users, they expect to be able to set a specific node version instead of only a major.

Currently the only workaround I know of is to go spelunking in [nixpks repo](https://github.com/NixOS/nixpkgs/commits/master/pkgs/development/node-packages/node-packages.nix) and find the commit for a certain version and then pin that version in nixpacks.toml. But this process is almost impossible to explain to users.

```
[phases.setup]
nixpkgsArchive = 'bf85265bb302cdfe137e06bb207cb63aaaa726e8'
```

**Comment by flybayer** [comment]
Could we stop using nix for nodejs and instead use something like [fnm](https://github.com/Schniz/fnm) ?

**Comment by coffee-cup** [comment]
> Could we stop using nix for nodejs and instead use something like [fnm](https://github.com/Schniz/fnm) ?

Yes that is possible. Alternatively we could switch to something like [asdf](https://asdf-vm.com/).

It would be a pretty fundamental change to Nixpacks though. Which I am not against, but would just need to weigh the options and decide of moving away from Nix for managing packages is the best option for managing packages.

**Comment by supaspoida** [comment]
In case it's helpful, I've been using `rtx`, now renamed to `mise`, a rust replacement for/wrapper around the `asdf` ecosystem on top of nixpacks to add additional tools not supported directly. It is available via nixpkgs so I just add it to the `nixPkgs` in my `nixpacks.toml`.

https://mise.jdx.dev/

I'd love to see it baked into nixpacks somehow though, maybe as an optional layer on top of the existing setup?

**Comment by guathan** [comment]
I tried running the commit for version 22.12.0 to get Angular 20 running, but the deployment takes a long time (I'm using Coolify) and eventually I get the error "App\Jobs\ApplicationDeploymentJob has timed out."

Deployment failed. Removing the new version of your application.

I honestly don't know what else to do. I've been trying to deploy to my VPS for two days without success.

**Comment by iloveitaly** [comment]
@guathan 👋 I'm helping out with nixpacks/railpack maintenance!

We are deprecating nixpacks and replacing it with [railpack](https://github.com/railwayapp/railpack) (which supports ~all node versions). @supaspoida mentioned mise, and railpack is built on mise, so it allows you to specify X.X.Y node versions (even edge releases that are just a couple hours old).

Could you give a shot and let me know if you run into any issues?

**Comment by DimitriTsikaridze** [comment]
> I tried running the commit for version 22.12.0 to get Angular 20 running, but the deployment takes a long time (I'm using Coolify) and eventually I get the error "App\Jobs\ApplicationDeploymentJob has timed out."
> 
> Deployment failed. Removing the new version of your application.
> 
> I honestly don't know what else to do. I've been trying to deploy to my VPS for two days without success.

try using railpack it worked for me just RAILPACK_SPA_OUTPUT_DIR(if you're using SPA) and that's it

**Comment by marcoangelo** [comment]
I am still getting this issue. trying to use node v 24. specified the env variable NIXPACKS_NODE_VERSION=24, engine.node =24 in package.json
