### ISSUE TITLE
Haskell provider doesn't work on M1 macs

### ISSUE THREAD

**Issue by coffee-cup** [railwayapp/nixpacks#104]
Running Nixpackgs on the `examples/haskell-stack` directory fails with error

```
Unable to find installation URLs for OS key: linux-aarch64-tinfo6
```

It seems that the Haskell toolchain cannot find binaries for the aarch64 architecture on Linux

**Comment by aleksrutins** [comment]
That's really weird, as Stack should be building the toolchain from source (that's why it takes so long).

**Comment by coffee-cup** [comment]
Something somewhere is missing or not support on linux aarch machines. Not exactly sure why. I can take a deeper look into it later/tomorrow but wanted to create the issue in case anyone else had ideas.

**Comment by Milo123459** [comment]
Did you find out anything?

**Comment by aarnphm** [comment]
I can take a look into this if no one is working on this?

**Comment by aarnphm** [comment]
https://github.com/docker-library/docs/pull/2101/ seems like arm64 is not supported on haskell docker images yet. 

https://github.com/commercialhaskell/stack/issues/2103 This also seems to be an upstream stack issue to provide support for ARM64.
