### ISSUE TITLE
PHP 8.0 default Laravel build failing

### ISSUE THREAD

**Issue by christopherarter** [railwayapp/nixpacks#1040]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Getting a docker build failure for the default Laravel template:

```
#8 21.64          at /nix/store/lgcjj6s23v2203zyihsd0j26wh1saj0c-source/pkgs/build-support/trivial-builders/default.nix:88:7:
#8 21.64
#8 21.64            87|       inherit buildCommand name;
#8 21.64            88|       passAsFile = [ "buildCommand" ]
#8 21.64              |       ^
#8 21.64            89|         ++ (derivationArgs.passAsFile or []);
#8 21.64
#8 21.64        error: php80 has been dropped due to the lack of maintenance from upstream for future releases
```

### To reproduce

Start a new project and select the Laravel template.

### Expected behavior

Successful build

### Environment

version v1.20.0 on railway

**Comment by brody192** [comment]
php 8.0 is not supported anymore (whether intentionally or not)
please use php 8.1

**Comment by christopherarter** [comment]
@brody192 Should I report this in another Railway repo? It's the image used by the Railway template itself. I didn't select 8.0.

**Comment by brody192** [comment]
yes that repo is out of date, you would need to change the php version used in the composer file within your cloned repo

**Comment by christopherarter** [comment]
Ah ok, thank you!
