### ISSUE TITLE
Stream did not contain valid UTF-8

### ISSUE THREAD

**Issue by wp-coin** [railwayapp/nixpacks#1044]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I get an error when trying to build a WordPress app, some files cannot be read because of invalid UTF-8

### To reproduce

<img width="1091" alt="Screenshot 2024-01-11 220637" src="https://github.com/railwayapp/nixpacks/assets/35810228/7b55d71e-7251-4d46-bcd3-42012cb16ccd">

### Environment

Debian 12
[v1.16.0]

**Comment by zuchka** [comment]
glad you got unblocked @wp-coin. Closing this for now 👍

**Comment by wp-coin** [comment]
wrong, this is not fixed, there is a problem with utf-8 - 16 encoding, files are not recognized


Error: Error: Error reading web/core/tests/Drupal/Tests/Core/Asset/js_test_files/utf16_bom.js

Caused by:

stream did not contain valid UTF-8

========================================

Deployment failed. Removing the new version of your application.

**Comment by wp-coin** [comment]
this needs fixing ASAP!
