### ISSUE TITLE
Redis internal URLs cause build errors

### ISSUE THREAD

**Issue by x032205** [railwayapp/nixpacks#1089]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

When attempting to use a Redis internal URL, with both the Redis image and the app image running on the same docker network, I get a `getaddrinfo ENOTFOUND [Internal IP]` error:

![image](https://github.com/railwayapp/nixpacks/assets/120525481/f0ca8720-d9e7-4594-af39-0335ec52b099)

### To reproduce

Using [coolify](https://coolify.io/), create a Redis container and get an internal URL.

Example of internal URL:
`redis://:4bZB02N1qAYxzuCq23TfPtnV0hIOU3Ls5293UzzswWCflojrwGpTS9VHgzzDFmzB@137a13k4d3zd:6379/0`

Plug this URL into an env variable and attempt to build your web-app (that's on the same network) using nixpacks.

### Environment

Coolify v4
VPS runs Ubuntu 22.04 and is fully updated as of today.
Nixpacks image is ubuntu-1707782610

**Comment by brody192** [comment]
I'm not too sure this would be an issue with nixpacks, is the builder on coolify part of the private network?

**Comment by x032205** [comment]
> I'm not too sure this would be an issue with nixpacks, is the builder on coolify part of the private network?

If I'm not wrong, the builder is part of the network. When I asked about this issue in the Coolify support server, they said that the issue came from nixpacks.

**Comment by coffee-cup** [comment]
Can you please provide an example repo/code to reproduce this. Are you unable to connect to a separate Redis container during the build process?

**Comment by x032205** [comment]
> Can you please provide an example repo/code to reproduce this. Are you unable to connect to a separate Redis container during the build process?
Sadly I can't necessarily reproduce the code as a github repo, but I can provide step-by-step instructions on how to do it. And no, I am not able to connect to a seperate Redis container.

Several users have ran into the issue of not being able to connect to databases while building with nixpacks on coolify, so this could very well be a coolify issue. Sadly their server / github is no help, and I've gotten nearly no help in the past month.

One alternative I see would be to somehow prevent the usage of Redis during build time, and somehow delay it to be used after the app is built. I dont have much Redis experience so I have no idea if thats even possible.

To recreate this issue on ubuntu, follow these steps:
1. Install coolify using: `curl -fsSL https://cdn.coollabs.io/coolify/install.sh | bash`
2. Spin up a Redis instance through the coolify dashboard
3. Attempt to build any app that uses Redis. In my case it's a SvelteKit web app which uses the "redis" node library.

**Comment by brody192** [comment]
We can try ruling out nixpacks, can you try to build your app with a Dockerfile instead? if you get the same error then this would solely be a coolify issue.

**Comment by x032205** [comment]
But I still think that the issue is with coolify itself, not nixpacks. Others have said that this issue arises specifically when using nixpacks on coolify.

**Comment by x032205** [comment]
Okay I finally got a response and Coolify said they're working on it. I'm closing this issue because it's not a nixpacks issue.
