### ISSUE TITLE
Support for pnpm v9 

### ISSUE THREAD

**Issue by beefancohen** [railwayapp/nixpacks#1091]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When upgrading our service to use pnpm v9, nixpacks is still using pnpm v8

package.json
```
  "engines": {
    "node": "18.x"
  },
  "packageManager": "pnpm@9.0.3",
```

build logs
```
11:12:24 AM ╔══════════════════════════════ Nixpacks v1.21.3 ══════════════════════════════╗
11:12:24 AM ║ setup      │ nodejs_18, pnpm-8_x, openssl                                    ║
11:12:24 AM ║──────────────────────────────────────────────────────────────────────────────║
11:12:24 AM ║ install    │ pnpm dlx turbo prune --scope=tono-marketing && cd /app/out &&   ║
11:12:24 AM ║            │ pnpm install                                                    ║
11:12:24 AM ║──────────────────────────────────────────────────────────────────────────────║
11:12:24 AM ║ build      │ cd /app/out && pnpm dlx turbo run build                         ║
11:12:24 AM ║──────────────────────────────────────────────────────────────────────────────║
11:12:24 AM ║ start      │ cd /app/out && pnpm dlx turbo run start                         ║
11:12:24 AM ╚══════════════════════════════════════════════════════════════════════════════╝
11:12:24 AM 
```

### Expected behavior

Nixpacks (corepack by proxy) respects the `packageManager` field

### Environment

nixpacks version 1.21.3
aws codebuild

**Comment by coffee-cup** [comment]
Hmm Nixpacks should definitely be using corepack to install pnpm 9. Looks like we are not for pnpm for some reason.

**Comment by mrlubos** [comment]
I believe I have the same issue, downgrading to pnpm v8.x solved it for me :(

**Comment by gBusato** [comment]
> Have the same issue here on pnpm 9. Our service is in a monorepo, and the rest of the app depends on v9, so unfortunately can't downgrade to v8. Using a `nixpacks.toml` file installing v9 works:
> 
> ```
> providers = ["node"]
> 
> [phases.install]
> cmds = ["npm install -g corepack", "corepack enable", "corepack prepare pnpm@9.1.0 --activate", "pnpm install"]
> ```
> 
> However, would appreciate support for v9 out of the box.

Thanks for the tips, it did work for me !

**Comment by vitalybaev** [comment]
Apart from change in this repo it seems that https://github.com/railwayapp/nix-npm-overlay/pull/6 must be merged as well

**Comment by Thijmen** [comment]
@coffee-cup can we get some love on the above mentioned PR for `nix-npm-overlay`?  😄

**Comment by mrlubos** [comment]
Good stuff @coffee-cup 🚀
