### ISSUE TITLE
Nixpacks Feature Request: Python 3.12 Support

### ISSUE THREAD

**Issue by JacobCoffee** [railwayapp/nixpacks#1102]
### Feature request

3.11 is latest we support, 3.12 was released Oct. 2023, 3.13 beta 1 is now out

### Motivation

Faster, latest, project doesn't have to conform CI and local testing just for Railway deploys.

### Contribution

Possibly, I have https://github.com/JacobCoffee/nixpacks/pull/1/files but I'm not super familiar with the repo and unsure how much more would be required (test suite, etc.)

**Comment by vincentdavis** [comment]
Please add 3.12
