### ISSUE TITLE
Nixpacks Bug Report

### ISSUE THREAD

**Issue by vitusan** [railwayapp/nixpacks#1156]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Every docker image built with Nixpacks using my stack (NestJS + MongoDB + Passport) ends up in a SIGILL termination. Don't know if the issue is with Nixpacks itself or the underlying structure (Coolify) orchestrating the build and execution process.

The error presented is this: "Command was killed with SIGILL (Invalid machine instruction): /tmp/yarn--1722899316954-0.961741874653044/node dist/main", witch came from the logs inside the container. 

Seems it crashes when i try to authenticate through any sort of strategy available in Passport. I've tried using Api Key auth, JWT bearer auth, and always when i call the auth endpoint it crashes, but only the endpoint witch are guarded and require auth. The rest of the REST API is fine, no other endpoint generates the SIGILL, just the auth endpoints.

Tried executing the same code running on a pm2 instance and everything worked out just fine, the whole authentication process included.

### To reproduce

1. Create app with nest cli
2. Add api key auth flow 
3. Create endpoints to interact with the authentication
4. Upload app to git and deploy it using Coolify
5. Execute said endpoints
6. Get SIGILL error inside container logs

### Expected behavior

Don't present the SIGILL error.

### Environment

Coolify [v4.0.0-beta.319](https://github.com/coollabsio/coolify/releases/tag/v4.0.0-beta.319)
Nixpacks [v1.24.1](https://github.com/railwayapp/nixpacks/releases/tag/v1.24.1)
Ubuntu 20.04

Package.json: 

{"dependencies": {
        "@nestjs/cache-manager": "^2.2.2",
        "@nestjs/common": "^10.0.0",
        "@nestjs/core": "^10.0.0",
        "@nestjs/event-emitter": "^2.0.4",
        "@nestjs/passport": "^10.0.3",
        "@nestjs/platform-express": "^10.0.0",
        "@nestjs/swagger": "^7.4.0",
        "@nestjs/throttler": "^6.0.0",
        "cache-manager": "^5.7.4",
        "class-transformer": "^0.5.1",
        "class-validator": "^0.14.1",
        "crypto-js": "^4.2.0",
        "mongoose": "^8.5.2",
        "passport": "^0.7.0",
        "passport-headerapikey": "^1.2.2",
        "puppeteer": "^22.15.0",
        "qrcode": "^1.5.3",
        "reflect-metadata": "^0.2.0",
        "rxjs": "^7.8.1",
        "whatsapp-web.js": "^1.25.0",
        "wwebjs-mongo": "^1.1.0"
    },
    "devDependencies": {
        "@dotenvx/dotenvx": "^1.6.4",
        "@nestjs/cli": "^10.0.0",
        "@nestjs/schematics": "^10.0.0",
        "@nestjs/testing": "^10.0.0",
        "@types/express": "^4.17.17",
        "@types/jest": "^29.5.2",
        "@types/node": "^20.3.1",
        "@types/qrcode": "^1.5.5",
        "@types/supertest": "^6.0.0",
        "@typescript-eslint/eslint-plugin": "^6.0.0",
        "@typescript-eslint/parser": "^6.0.0",
        "eslint": "^8.42.0",
        "eslint-config-prettier": "^9.0.0",
        "eslint-plugin-prettier": "^5.0.0",
        "jest": "^29.5.0",
        "prettier": "^3.0.0",
        "source-map-support": "^0.5.21",
        "supertest": "^6.3.3",
        "ts-jest": "^29.1.0",
        "ts-loader": "^9.4.3",
        "ts-node": "^10.9.1",
        "tsconfig-paths": "^4.2.0",
        "typescript": "^5.1.3"
    }}

**Comment by vitusan** [comment]
Solved, it is a bug in dotenvx. I just won't play nice with docker yet. Waiting for updates.

**Comment by motdotla** [comment]
@vitusan do you know where the SIGILL is originating from? dotenvx only calls debug on a SIGILL at the moment. https://github.com/dotenvx/dotenvx/blob/1d005b7d7687bb5c7a85684dc1cca5920e5583ce/src/lib/helpers/executeCommand.js#L8

**Comment by vitusan** [comment]
well, @motdotla, it was running inside a container created with nixpacks, but funny enough, this behavior only happened when inside a container. Running the very same code in bare metal, nothing like this happened. And all it took was a call to an endpoint that handled auth. But the NestJs app was indeed using other variables, and the app seemed to work without any problem. The app would start and run stable. Well, the variables seemed to match the .env declarations, everything checks. So i don't really know where it came from, except when my code tried to access the endpoint containing the said auth variable decrypted with dotenvx, things would break with a SIGILL. Best i can do is upload a sample repo and ask that you try to deploy it with coolify with the same setup.

**Comment by motdotla** [comment]
thanks, keep me posted.
