### ISSUE TITLE
Esy Provider

### ISSUE THREAD

**Issue by aleksrutins** [railwayapp/nixpacks#126]
<https://reasonml.github.io>
<https://esy.sh>

**Comment by Milo123459** [comment]
Potentially one for https://dune.build/ as well?

**Comment by aleksrutins** [comment]
I was thinking that that could maybe be covered by #114.

**Comment by Milo123459** [comment]
Esy is basically exclusively used for OCaml, right?

**Comment by aleksrutins** [comment]
Esy is used for either OCaml or Reason.
