### ISSUE TITLE
Check for `Deno.` APIs in Deno provider

### ISSUE THREAD

**Issue by Milo123459** [railwayapp/nixpacks#128]
Check if any `Deno.` APIs are being used in the Deno provider.

**Comment by coffee-cup** [comment]
I'm not sure if we should have this change. Just using regex to check for `Deno.*` usage can easily go wrong (variable named `Deno` in normal Node). Alternative is to actually parse all the source code and look for top level usage of the Deno variable. But I'm not sure that is something that Nixpacks should be doing. Is it common to be just using `Deno`, in an app that should be built and deployed, but is not also using a Deno import or has a `deno.json` file?
