### ISSUE TITLE
Windows binary assets are broken

### ISSUE THREAD

**Issue by coffee-cup** [railwayapp/nixpacks#131]
The release action fails to create and upload a binary for Windows (e.g. https://github.com/railwayapp/nixpacks/releases/tag/v0.0.15). I think it has something to do with how we use [7zip](https://github.com/railwayapp/nixpacks/blob/main/.github/workflows/release.yml#L118).

JR can fix this one soon. Creating issue to track it.

**Comment by devtomio** [comment]
The problem lies in https://github.com/railwayapp/nixpacks/blob/main/.github/workflows/release.yml#L138, `7z` generates a `.zip` file.
