### ISSUE TITLE
Static file root should be relative to app source

### ISSUE THREAD

**Issue by coffee-cup** [railwayapp/nixpacks#170]
When specifying a directory to serve with the static file provider, you have to prefix with `/app`. The user should not have to know anything about the directory structure inside the docker container. Specifying `root: public` should actually serve `/app/public`

**Comment by wyzlle** [comment]
Agreed. Wanted to make that change. But PR was merged lol.

**Comment by JakeCooper** [comment]
/app/public is how the Staticfile CNBP works though right? I think we should keep it consistent?

**Comment by wyzlle** [comment]
Yes

**Comment by JakeCooper** [comment]
Yea so, for users who know how Staticfiles work I don't think we should change anything

If we really want a truly "Don't think about filestructure" experience, IMO we should just use `index.html` or `static` or `public` and autoserve those. Thoughts?
