### ISSUE TITLE
Allow increased Nix package configuration in generated Nix expression

### ISSUE THREAD

**Issue by aleksrutins** [railwayapp/nixpacks#183]
Currently, providers are not able to access the `environment.nix` generated by Nixpacks. However, this can cause some problems, because Nix uses weird hashed paths for things and the only way to get those paths (that I know of) is to use APIs that are available only to Nix expressions. For instance, the PHP provider needs FastCGI to be available in order to actually serve PHP. However, it can't find the socket, since it's at one of the aforementioned weird paths, instead of at `/var/run/php/php8.1-fpm.socket`, where the system NGINX configuration expects it to be.

**Comment by JakeCooper** [comment]
Shouldn't we just be adding FastCGI as a dep and then letting nix do it's thing for de-duping/resolution?

**Comment by coffee-cup** [comment]
Can you provide a more concrete example of how accessing `environment.nix` would help.

The providers are the things that generate the Nix expression so it is kind of a chicken and egg problem. If a dep is needed ideally it can be added (like Cooper mentioned) as a dep.

**Comment by aleksrutins** [comment]
What I meant is specifically being able to write custom Nix code into `environment.nix`, not reading it. For instance, the [Nix documentation for `php-fpm`](https://nixos.wiki/wiki/Phpfpm) has a great big block of necessary configuration, separate from the packages.

I might be misunderstanding the purpose of `environment.nix`, though - is it for both packages and configuration, or just for packages?

**Comment by coffee-cup** [comment]
Ah okay, that makes sense. Yes ideally we can provide additional config to Nix packages like this. The `Pkg` type currently has support for overrides and overlays. But in this case a lot more configuration is required. I think we can extend the `Pkg` type to support this so you can add a Nix package with predefined configuration to the build.

**Comment by coffee-cup** [comment]
After looking at the php-fmp configuration a bit more it looks like it would only work for NixOS, which is not what nixpacks uses. I do still agree that additional configuration in the generated Nix expression is necessary.

**Comment by coffee-cup** [comment]
Going to close this as there is nothing concrete that can be added. I am all for more configuration via Nix expressions, but a separate issue can be opened for each type of configuration requested.
