### ISSUE TITLE
Organise examples directory

### ISSUE THREAD

**Issue by Milo123459** [railwayapp/nixpacks#186]
Each provider should have it's own directory, and in that directory it will have directories containing examples.

**Comment by coffee-cup** [comment]
Any reason for this? In the future we might allow matching multiple providers which wouldn't really work with sub directories. IMO prefixing the example directory with "language-*" is fairly clear.

**Comment by wyzlle** [comment]
> Each provider should have it's own directory, and in that directory it will have directories containing examples.

I'll be against this I prefer the way it is right now. In the future we can probably have a separate repo that contains examples with railway button.

**Comment by Milo123459** [comment]
It would just be beneficial to organise it more.

**Comment by wyzlle** [comment]
Examples are used for testing. Idt they were ever designed to work as starters. All examples have different edge cases.

**Comment by Milo123459** [comment]
Examples != staters. Examples, are basically glorified tests and aren't sorted. I want to sort them into subdirectories.

**Comment by coffee-cup** [comment]
I personally prefer a single directory to test against. Easier to run too as it is flat (examples/thing)

<img width="365" alt="image" src="https://user-images.githubusercontent.com/3044853/172228913-24f4b379-b87b-4ec8-b21f-86b2037a974b.png">

**Comment by Milo123459** [comment]
In that case, can we potentially make yarn, pnpm and npm directories start with node-?

**Comment by coffee-cup** [comment]
> In that case, can we potentially make yarn, pnpm and npm directories start with node-?

Yeah that is not a bad idea

**Comment by coffee-cup** [comment]
Can I assign this to you @Milo123459 ?

**Comment by Milo123459** [comment]
Yup
