### ISSUE TITLE
Support nohoist in yarn workspaces

### ISSUE THREAD

**Issue by coffee-cup** [railwayapp/nixpacks#192]
https://classic.yarnpkg.com/blog/2018/02/15/nohoist/

If the `workspaces` field of `package.json` is shaped like the following

```ts
export type WorkspacesConfig = {
  packages?: Array<string>,
  nohoist?: Array<string>,
};
```

our current Node provider crashes. However, this is a completely valid package json and yarn workspace format that we should support.

**Comment by Milo123459** [comment]
Would you mind sharing crash logs?

**Comment by coffee-cup** [comment]
> Would you mind sharing crash logs?

Np!

The Discord thread is here https://canary.discord.com/channels/713503345364697088/960605685920452669/983746632338276353

<img width="972" alt="image" src="https://user-images.githubusercontent.com/3044853/172449680-941f0a27-1641-4853-8db5-59d0c4fbdb1b.png">


The problem is that we parse the `"workspaces"` field into an array but it can optionally be an object.

https://github.com/railwayapp/nixpacks/blob/main/src/providers/node.rs#L22

**Comment by Milo123459** [comment]
Why are we actually parsing the workspaces? It does nothing as far as I can see in the code.
