### ISSUE TITLE
has_dependency function for package.json

### ISSUE THREAD

**Issue by Milo123459** [railwayapp/nixpacks#201]
Function to check if package manifest / lockfile contains a dependency. Should check `devDependencies`, `dependencies` and `peerDependencies`

**Comment by wyzlle** [comment]
Checking only `dependencies` won't be the right thing here as railway installs `devDependencies` too. And you'll also have to check lockfiles to find if some other library in that project is dependent on it.

**Comment by coffee-cup** [comment]
> Checking only `devDependencies`, `dependencies` and `peerDependencies` won't be sufficient here as It'll fail to detect dependent packages in projects that have no lockfile. Instead one should use npm's API

It is still useful to check deps in `package.json`. Checking if the projects use NextJS, Cypress, Remix, etc. It is implemented in #259
