### ISSUE TITLE
Automate Release Management

### ISSUE THREAD

**Issue by JakeCooper** [railwayapp/nixpacks#232]
Would be awesome if, similar to how the CLI has a release on tags, that we ran `cargo release major|minor|patch` when a PR with a tag was merged in

**Comment by devtomio** [comment]
there's https://github.com/google-github-actions/release-please-action but it requires us to switch to conventional commits

**Comment by nebulatgs** [comment]
> Would be awesome if, similar to how the CLI has a release on tags, that we ran `cargo release major|minor|patch` when a PR with a tag was merged in

Would the tag be in the form of `vMAJOR.MINOR.PATCH`?
