### ISSUE TITLE
Using multiple providers

### ISSUE THREAD

**Issue by ipmb** [railwayapp/nixpacks#237]
I have a project that uses both Node.js and Python. With buildpacks, I could specify `heroku/nodejs` and `heroku/python` and it would do the right thing (Node build/install followed by Python build/install).

With nixpacks, the project is identified as Node.js automatically and does the right thing there, but if I add `--pkgs=python39` to `nixpack build` it only installs Python, but doesn't use the default build/install command.

Is there a way to "stack" providers similar to how it is done with buildpacks? If not, that would be nice to have so I don't have to manually specify the additional build/install commands.

**Comment by JakeCooper** [comment]
> Is there a way to "stack" providers similar to how it is done with buildpacks? If not, that would be nice to have so I don't have to manually specify the additional build/install commands.

ATM no, you'd have to manually define those additional commands which I could see as being not so great. Simply haven't run into in a way that doesn't "rollup" to framework specific handling (e.g Ruby runs some node stuff but that's invoked from the Ruby provider)

**Comment by JakeCooper** [comment]
I don't want to jinx it, but we might be able to accomplish this by simply:
- Changing `[matched_provider](https://github.com/railwayapp/nixpacks/blob/59ba5914e411b778b015da4bb6374826ffc16825/src/nixpacks/plan/generator.rs#L89)` from an Option to a Vec
- Writing a function to "join" each stage

Would be open to a PR or we can look at it once there's more demand in that category

**Comment by ipmb** [comment]
This is a pretty common use case for Django (and I assume Python in general). Use a standard Node.js pipeline for your static frontend assets and then build your Python project. For Django, you'd typically run `manage.py collectstatic --noinput` at the end to grab all the Node-built files and put them where Django expects. The Heroku buildpack runs this collectstatic step by default, but it has a toggle to turn it off because it can be problematic in some scenarios.

**Comment by Finkregh** [comment]
I think that's a common usecase for many web related projects.
One half the actual software and the other half some nodejs to build assets.

**Comment by JakeCooper** [comment]
> This is a pretty common use case for Django (and I assume Python in general). Use a standard Node.js pipeline for your static frontend assets and then build your Python project. For Django, you'd typically run manage.py collectstatic --noinput at the end to grab all the Node-built files and put them where Django expects. The Heroku buildpack runs this collectstatic step by default, but it has a toggle to turn it off because it can be problematic in some scenarios.

Right. Like I said, the Ruby/Rails Provider generally handles this, so I wouldn't be opposed to adding one of:
- Logic for multiple providers to contribute
- The above into the Django provider itself

**Comment by coffee-cup** [comment]
I will start working on this soon. It is a bit more complicated then just converting it to a Vec and the ordering of these providers will be important.

It would also be nice if you could specify the exact providers to use via a config variable or something.
