### ISSUE TITLE
ASDF Provider: Support for .tool-versions

### ISSUE THREAD

**Issue by ipmb** [railwayapp/nixpacks#238]
Feature request: If a [`.tool-versions`](https://asdf-vm.com/manage/configuration.html#tool-versions) file (used by `asdf`) is in the root of the directory, use the providers and versions it defines.

**Comment by Milo123459** [comment]
We don't use asdf anywhere fwiw

**Comment by ipmb** [comment]
Just to clarify, my suggestion isn't that asdf is used to install the necessary packages. Instead that the `.tool-versions` file used by asdf could be used to determine providers and versions.

Here's an example `.tool-versions` file:

```
python 3.8.12
nodejs 16.14.2
```

My suggestion is that nixpacks could read this file and then know to use the nodejs provider and python provider with the versions specified. #237 is somewhat related.

**Comment by Milo123459** [comment]
So we just need to parse that file. In that case, this is the same as parsing `.node-version`, but we just need to find a line that starts with `nodejs` and get that version. (this was just an example)

Should the title of the issue be changed?

**Comment by Milo123459** [comment]
Going to make a function on app called `read_tool_versions` which takes a regex for matching the version. Should the version inside .tool-versions take priority over environment variables and something like the engines field in package.json?

**Comment by ipmb** [comment]
My 2¢, it should be lower on the priority list. `asdf` is primarily used for local development environments afaik. So, it can serve as a good hint about what to use, but it should be easy for folks to override if they want to. A specific use case might be if you always want to run the latest node `16.x`. I don't think `asdf` supports that, so a user might want to specify that in nixpacks over the pinned version in `.tool-versiosn`

**Comment by Milo123459** [comment]
Good idea! In the spectrum of priority it'll be at the lowest.

**Comment by coffee-cup** [comment]
Closing in favour of the discussion item https://github.com/railwayapp/nixpacks/discussions/245.

**Comment by flybayer** [comment]
I would also like support for `.tool-versions`. We've had users expect that this would be used by default for version detection.
