### ISSUE TITLE
Environment variable support

### ISSUE THREAD

**Issue by coffee-cup** [railwayapp/nixpacks#24]
Much like docker and pack, you should be able to provide environment variables that will be available to the build.

I am thinking they can be supplied with the flag

```
--env "NAME=value" EXTERNAL
```

In the NAME=value case, the variable NAME is set to "value". In the second case, the variable EXTERNAL is provided from the calling environment.

**Comment by Milo123459** [comment]
Perhaps also specify a `.env` file that could be loaded?
