### ISSUE TITLE
Add to nixpkgs

### ISSUE THREAD

**Issue by frontsideair** [railwayapp/nixpacks#251]
It would be great to see this package in nixpkgs. I use Nix on macOS instead of Homebrew and I personally would like Nix installation option.

**Comment by devtomio** [comment]
I'll be working on this.

**Comment by zoedsoupe** [comment]
I already added https://github.com/NixOS/nixpkgs/pull/179932

**Comment by zoedsoupe** [comment]
It's already on `master` branch, for unstable: https://github.com/NixOS/nixpkgs/pull/179932

**Comment by frontsideair** [comment]
Great work!
