### ISSUE TITLE
Support Rust workspace Cargo.toml

### ISSUE THREAD

**Issue by MolotovCherry** [railwayapp/nixpacks#256]
Tried this under Railway, but when your `Cargo.toml` is a workspace one, it doesn't work. It however should be allowed. Building a workspace will build all members, and while that may be not ideal, starting a binary will still work with it since it'll get generated. A person can also provide a custom build command targeting only one package when that's undesired behavior,  
`cargo build --release -p package-name`

```
Error: Generating start phase
 
Caused by:
 
0: Reading Cargo.toml
1: missing field `package` at line 1 column 1
```

**Comment by devtomio** [comment]
will work on this

cc @Milo123459
