### ISSUE TITLE
docs: When to use nixpacks over buildpacks 

### ISSUE THREAD

**Issue by dolfolife** [railwayapp/nixpacks#260]
# Ask

As an external user I want to understand when I should be using nixpacks or "what type of issues are addressed by this project"

# context 

I read 

```
alternative to [Buildpacks](https://buildpacks.io/) and attempts to address a lot of the shortcomings and issues that occurred when deploying thousands of user-apps to the Railway platform
```

and I would like to get context over what I am gaining testing this.

**Comment by nebulatgs** [comment]
Nixpacks is overall a much better choice, since it's officially maintained by Railway, rather than a 3rd party. Plus it can build many different languages, and handles edge cases much better than Buildpacks.
