### ISSUE TITLE
RFC: File based config

### ISSUE THREAD

**Issue by coffee-cup** [railwayapp/nixpacks#27]
Nixpacks configuration should be able to be provided through a file on disk in the app source. The main benefit is that build configuration can be tracked through source control.

At the moment, the configurable options are

- Nixpkgs to install
- Build command
- Start command

A very basic format for these options is a JSON file

```json
{
  "packages": ["pkgs.cowsay", "pkgs.lolcat"],
  "startCommand": "...",
  "buildCommand": "..."
}
```

**Comment by aleksrutins** [comment]
Would it be feasible to do this through a `.nix` file? In my opinion, the declarative configuration syntax is one of Nix's greatest strengths, and it would be great to integrate that with Nixpacks. I don't know how it would be implemented, and I don't know that much about Nix, but I was thinking about something along these lines in terms of syntax:
```nix
{stdenv, nixpacks}: rec {
  derivation = stdenv.mkDerivation {
    # ...
  };
  deploy = nixpacks.configure {
    inherit derivation;
    startCommand = "./whatever";
    # Since the package is already built by the derivation, you shouldn't need a separate build command here
  };
}
```
Or something like that.

**Comment by coffee-cup** [comment]
That could work. And I do think it is a good idea to be able to import/build Nix projects with zero-config. However, I am not sure this is the right approach for all projects. Ideally, users can use all features of Nixpacks without having to know and understand the Nix expression language (see core ideas in readme). This is also something you have to opt into completely and means that if you want to save the start command to version control you will have to also figure out how to build your app with Nix and cannot take advantage of the providers.

That being said, looking for and building a `default.nix` or a `flake.nix` is a great idea. We could have a `NixProvider` that does this.

**Comment by aleksrutins** [comment]
An idea: if Nixpacks were to export some sort of interface to Nix expressions, then would it be possible to also export the providers? Maybe even provide some sort of wrapper around `mkDerivation`, to allow the user to have the best of both worlds (zero-config Nix expressions)? Something like this, maybe:
```nix
{nixpacks, stdenv, myDependency}:
nixpacks.mkDerivation {
  # All options are optional; `extends` would default to stdenv, most likely.
  extends = stdenv;
  buildCommand = "whatever";
  runCommand = "./whatever";
  packages = [ myDependency ];
}
```

That might take whatever the `extends` option is and then wrap `extends.mkDependency` with the required build steps and dependencies.

**Comment by coffee-cup** [comment]
Oh yeah that is a neat idea. It would allow us to leverage the Nix ecosystem a bit more too. I'll play around with it.

**Comment by wyzlle** [comment]
Moved to discussions (#120)
