### ISSUE TITLE
Improve Procfile parsing

### ISSUE THREAD

**Issue by coffee-cup** [railwayapp/nixpacks#28]
The `Procfile` parsing is very basic at the moment. We should look for and use other process types besides "web" if web is not found. If more than a single process type is found, we should also warn/error to provide feedback to the user.

**Comment by Milo123459** [comment]
Couldn't we also just do something like converting `worker:` to `web:`? 

Side note, I'm pretty sure you can provide a web and worker process type, so it may not work. Ideally, we should support worker and web.

**Comment by coffee-cup** [comment]
It comes down to how these processes are being run (which is in Docker at the moment). 1 process per container makes logging, metrics, error handling, and a few other things much simpler. It is also the preferred way of running code on Railway (for more than 1 process you can spin up another service). However, there is no reason to completely ignore the `worker` process type if it is the only type found in the Procfile and can simply use that as the start command.

Supporting Procfiles in this case is more about being (90%) backward compatible with what currently exists as a way to override the start command per app (in Railway and Heroku). For more control see #27.

**Comment by devtomio** [comment]
Could use https://crates.io/crates/procfile/ for this
