### ISSUE TITLE
nixpacks/node: persist volume across deployments

### ISSUE THREAD

**Issue by exponent42** [railwayapp/nixpacks#297]
Normally would define a volume in the dockerfile, however can't see anything mentioned in the docs about this. 

Summary: 
Looking to keep contents inside a `/dist/assets` folder within the base dir, so it'll persist between deployments.

**Comment by coffee-cup** [comment]
Is this a request for the Nixpacks tool itself or for building with Nixpacks on Railway?

**Comment by coffee-cup** [comment]
Mounting volumes are not supported on Nixpacks at the moment. `-v` and `--volume` would be good flags.

**Comment by coffee-cup** [comment]
This doesn't really make sense for Nixpacks to handle. Volumes are used when running the container, not when creating the image. Going to close this for now, but please lmk if you were thinking of something different.
