### ISSUE TITLE
Cache Java/Maven dependencies

### ISSUE THREAD

**Issue by coffee-cup** [railwayapp/nixpacks#307]
Java deps take a while to download and install. We should be caching them between builds.

**Comment by aarnphm** [comment]
One solution is to not assign cache key for java. BuildKit cache for java can then be shared between builds.

**Comment by coffee-cup** [comment]
I'm not sure what you mean? The problem right now is that no directories are specified to cache during the build. We should do something like this https://github.com/railwayapp/nixpacks/blob/main/src/providers/node.rs#L71 to indicate which directory we want buildkit to cache.

**Comment by aarnphm** [comment]
I believe we are assigning buildkit cache id right? I'm saying for java usecase, we probably don't need that?.

**Comment by coffee-cup** [comment]
> I believe we are assigning buildkit cache id right?

Ya that is correct. I've just noticed that Java/Maven builds can take a long time sometimes so was thinking we could improve the by caching something. I haven't been in the Java ecosystem in a while though so not sure if there is a standard directory to cache.

**Comment by Sohalt** [comment]
Dependencies should end up in `~/.m2/repository`, so that's probably what you want to cache.
