### ISSUE TITLE
Include libmysqlclient for Rust's Diesel ORM MySQL Builds

### ISSUE THREAD

**Issue by FinnDore** [railwayapp/nixpacks#328]
### Feature request

The automatic inclusion and linking of libmysqlclient when using diesel orm with mysql.

### Motivation

Currently im using [diesel](https://diesel.rs/) with a mysql database, this requires me to have a version of libmysqlclient when building my binaries. Usually i achieve this (on mac) by running `brew install mysql-client`, then when building the binaries i would set the following env var `USTFLAGS="-L/opt/homebrew/opt/mysql-client/lib"`.

While using railway ive tried installing a similar package however as of current i cant find one that includes libmysqlclient. I did find [this](https://packages.debian.org/sid/libmysqlclient21) but unfortunately i cant install it on railway as its not there.

### Contribution

Quite new to rust, and im not sure where to start here tbh as its not just a rust issue i dont think.

**Comment by aleksrutins** [comment]
Try setting `NIXPACKS_APT_PKGS=libmysqlclient-dev` as an environment variable.

**Comment by Milo123459** [comment]
Just to be clear, is this package a MySQL server (something that runs the database) or just a connector? I've looked at the package but I'm rather confused.

**Comment by FinnDore** [comment]
> libmysqlclient-dev

Unfortunately that does not seem to be an installable package.

`
#12 3.614 Reading state information...
#12 3.653 Package libmysqlclient-dev is not available, but is referred to by another package.
#12 3.653 This may mean that the package is missing, has been obsoleted, or
#12 3.653 is only available from another source
#12 3.653 However the following packages replace it:
#12 3.653   libmariadb-dev-compat libmariadb-dev
#12 3.653
 
#12 3.744 E: Package 'libmysqlclient-dev' has no installation candidate
`

**Comment by FinnDore** [comment]
> Try `libmariadb-dev` instead.

Still the same,

truncated error message from cargo build: `#14 34.50   = note: /nix/store/f0rrfmf8kh5bsiql5bbq7m4h3xgihpnx-binutils-2.38/bin/ld: cannot find -lmysqlclient: No such file or directory`.

Looking at the package it does not seem to install libmysqlclient either. There is a maria specific one but that most likely wont work.

```
#14 4.423 /.
#14 4.423 /usr
#14 4.423 /usr/bin
#14 4.423 /usr/bin/mariadb_config
#14 4.423 /usr/include
#14 4.423 /usr/include/mariadb
#14 4.423 /usr/include/mariadb/errmsg.h
#14 4.423 /usr/include/mariadb/ma_list.h
#14 4.423 /usr/include/mariadb/ma_pvio.h
#14 4.423 /usr/include/mariadb/ma_tls.h
#14 4.423 /usr/include/mariadb/mariadb
#14 4.423 /usr/include/mariadb/mariadb/ma_io.h
#14 4.423 /usr/include/mariadb/mariadb_com.h
#14 4.423 /usr/include/mariadb/mariadb_ctype.h
#14 4.423 /usr/include/mariadb/mariadb_dyncol.h
#14 4.423 /usr/include/mariadb/mariadb_rpl.h
 
#14 4.423 /usr/include/mariadb/mariadb_stmt.h
#14 4.423 /usr/include/mariadb/mariadb_version.h
#14 4.423 /usr/include/mariadb/my_config.h
#14 4.423 /usr/include/mariadb/my_global.h
#14 4.423 /usr/include/mariadb/my_sys.h
#14 4.423 /usr/include/mariadb/mysql
#14 4.423 /usr/include/mariadb/mysql/client_plugin.h
#14 4.423 /usr/include/mariadb/mysql/plugin_auth.h
#14 4.423 /usr/include/mariadb/mysql/plugin_auth_common.h
#14 4.423 /usr/include/mariadb/mysql.h
#14 4.423 /usr/include/mariadb/mysql_com.h
#14 4.423 /usr/include/mariadb/mysql_version.h
#14 4.423 /usr/include/mariadb/mysqld_error.h
#14 4.423 /usr/lib
#14 4.423 /usr/lib/x86_64-linux-gnu
#14 4.423 /usr/lib/x86_64-linux-gnu/libmariadb.a
#14 4.423 /usr/lib/x86_64-linux-gnu/libmysqlservices.a
#14 4.423 /usr/lib/x86_64-linux-gnu/pkgconfig
#14 4.423 /usr/lib/x86_64-linux-gnu/pkgconfig/libmariadb.pc
#14 4.423 /usr/share
#14 4.423 /usr/share/aclocal
#14 4.423 /usr/share/aclocal/mysql.m4
#14 4.423 /usr/share/doc
#14 4.423 /usr/share/doc/libmariadb-dev
#14 4.423 /usr/share/doc/libmariadb-dev/changelog.Debian.gz
#14 4.423 /usr/share/doc/libmariadb-dev/copyright
#14 4.423 /usr/share/doc/libmariadb-dev/examples
#14 4.423 /usr/share/doc/libmariadb-dev/examples/udf_example.c.gz
#14 4.423 /usr/share/lintian
#14 4.423 /usr/share/lintian/overrides
#14 4.423 /usr/share/lintian/overrides/libmariadb-dev
#14 4.423 /usr/share/man
#14 4.423 /usr/share/man/man1
#14 4.423 /usr/share/man/man1/mysql_config.1.gz
#14 4.423 /usr/bin/mariadb-config
#14 4.423 /usr/lib/x86_64-linux-gnu/libmariadb.so
#14 4.423 /usr/lib/x86_64-linux-gnu/libmariadbclient.a
#14 4.423 /usr/lib/x86_64-linux-gnu/libmariadbclient.so
#14 4.423 /usr/lib/x86_64-linux-gnu/pkgconfig/mariadb.pc
#14 4.423 /usr/share/man/man1/mariadb-config.1.gz
#14 4.423 /usr/share/man/man1/mariadb_config.1.gz
```

**Comment by aleksrutins** [comment]
Try `libmariadb-dev-compat`.

**Comment by FinnDore** [comment]
Still no luck.

I have tried multiple variations of the rust flags i use locally e.g: `-L/usr/lib/x86_64-linux-gnu/libmysqlcppconn-static.a` | -`-L/usr/lib/x86_64-linux-gnu/` so forth and so on.

**Comment by FinnDore** [comment]
Tried all three the last two gives the following error probally due to the filepath parsing.

`
#11 3.042 error: attribute 'so' missing
#11 3.042
#11 3.042        at /app/environment.nix:6:52:
#11 3.042
#11 3.042             5|   let
#11 3.042             6|     APPEND_LIBRARY_PATH = "${lib.makeLibraryPath [ libmysqlclient.so ] }";
#11 3.042              |                                                    ^
#11 3.042             7|     myLibraries = writeText "libraries" ''
#11 3.042        Did you mean src?
`

The first one seemed to install, where do they get placed? I think if i replace RUSTFLAGS="-L/opt/homebrew/opt/mysql-client/lib" with the correct path it should work.

**Comment by aleksrutins** [comment]
Try `NIXPACKS_PKGS=libmysqlclient` and `NIXPACKS_LIBS=libmysqlclient`.

**Comment by FinnDore** [comment]
That didn't work either unfortunately.

**Comment by FinnDore** [comment]
Might be worth noting my build command looks like this `cargo build --target=x86_64-unknown-linux-musl --features vendored` to fix https://github.com/railwayapp/nixpacks/issues/286

**Comment by FinnDore** [comment]
Ive created a demo app to help reproduce the issue if its helpfull.
You will have to alter the root dir to /apps/something. For some reason the template does not retain the root i set.
[![Deploy on Railway](https://railway.app/button.svg)](https://railway.app/new/template/xKUJiI?referralCode=64JXqe)

**Comment by FinnDore** [comment]
Just in the process of creating a test for this. https://github.com/FinnDore/nixpacks/tree/rust-diesel-libmysqlclient.

**Comment by JakeCooper** [comment]
@FinnDore Not to have you play "dependency battleship" again but can you try `NIXPACKS_PKGS=default-libmysqlclient-dev`

**Comment by FinnDore** [comment]
Day 120 if libmysql-client living rent free. As a background task im looking into this.

Following on from Jakes pr ( thanks for splitting out the tests  😍).

I noticed that with [rusts](https://hub.docker.com/_/rust) docker image it just works. Jr mentioned that they must install the right deps in the right places. Crucially when building a binary in rusts container then copying that binary into a debian:buster-slim and then re installing the correct deps ( like `libmariadb-dev` ) in a debain:buster-slim it runs fine. 

I did some digging and under the hood they use [buildpack-deps](https://hub.docker.com/_/buildpack-deps) which installs  a cursed amount of deps, the relevant ones being `libpq-dev`, `libsqlite3-dev` (`default-libmysqlclient-dev` or `libmysqlclient-dev` see [here](https://github.com/docker-library/buildpack-deps/blob/05f953e83c543d38f108d3c31ab50715c21c8d7f/debian/buster/Dockerfile#L55) . [This link might also be of help later on](https://lists.debian.org/debian-devel-announce/2016/09/msg00000.html) )

Another thing of note is that `libmysqlclient-dev` and `libmariadb-dev` appear to be interchangeable! As `buildpack-deps` use `default-libmysqlclient-dev` and [here](https://github.com/FinnDore/something/blob/4c28ab65ea5999a70dc458577007dea3de40b005/apps/something/dockerfile#L19) i install `libmariadb-dev`.

My current approach is to hack together a container that runs using any means necessary. Then i can work backwards replacing the cursed parts with proper methods.
