### ISSUE TITLE
Support `deno.json` and import maps in Deno

### ISSUE THREAD

**Issue by aleksrutins** [railwayapp/nixpacks#33]
Deno has `deno.json`, which would be a pretty foolproof way to detect it (along with looking for TS/JS files). Also, Deno now has import maps, which allow for bare module specifiers, which means that the regex currently used for detection (which relies on the app importing modules from `https://deno.land/` via absolute URLs) won't necessarily work for all Deno apps.

**Comment by coffee-cup** [comment]
This is a good idea. The config file can also be used to start deno with.

For reference -> https://deno.land/manual/getting_started/configuration_file

**Comment by matthewmorek** [comment]
This doesn't seem to support path mappings:
```json
{
  "imports": {
    "@/": "./"
  }
}
```
It results in the following error:
```
error: Relative import path "@/middleware/notFound.ts" not prefixed with / or ./ or ../
```
