### ISSUE TITLE
Support Clojure deps.edn

### ISSUE THREAD

**Issue by Sohalt** [railwayapp/nixpacks#372]
### Feature request

It would be nice to support Clojure projects based on [deps.edn](https://clojure.org/guides/deps_and_cli) and [tools.build](https://clojure.org/guides/tools_build).
It's not exactly easy, since there are basically no constraints to what you can do in a `deps.edn` and how your build process looks, but it would be nice to have some heuristics to cover the most common use-cases (e.g. sth like `clojure -X:build`).

### Motivation

Currently only Clojure projects based on [leiningen](https://leiningen.org/) are supported.

### Contribution

I might look into this myself, if I find the time. I'll leave a comment here, before I start any work. In the meantime, if someone else wants to have a go, I'd be very grateful.

**Comment by AhmedMozaly** [comment]
Yes, deps.edn support is planned
Would also leave a comment when started!

**Comment by AhmedMozaly** [comment]
BTW, do you have reference repo to use while testing deps.edn support?
