### ISSUE TITLE
Python install relative packages

### ISSUE THREAD

**Issue by coffee-cup** [railwayapp/nixpacks#373]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When installing Python deps from the `requirements.txt` file we only copy over that file. However, this is a problem when installing relative dependencies. (https://canary.discord.com/channels/713503345364697088/872280248807469106/1002517924323545179)

We should copy over all files before installing so we can support this.

**Comment by Milo123459** [comment]
Rather then copying over all files, we can just detect when the `file:` protocol is used and just copy over the file after the protocol.

**Comment by astrojuanlu** [comment]
I confirm this fixed the issue 🎉 Thanks!
