### ISSUE TITLE
During the build step the environment variable `CI` seemingly isn't set to `true`

### ISSUE THREAD

**Issue by ChristianIvicevic** [railwayapp/nixpacks#379]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Over on Discord I already had a discussion with some of you noticing some problems with caching and building Nx monorepos since their daemon is running and SIGTERMing. According to https://github.com/nrwl/nx/issues/11395 I created in the Nx repo the daemon isn't starting if `CI=true` thus I was wondering whether Nixpacks or Railway even declare this variable to begin with during the build steps.

If not, it would be sensible to do so per default but you have to keep in mind that tools such as npm and others behave slightly different with that variable set to true.

### Expected behavior

Nixpacks and/or the Railway platform set `CI=true` during the build step.

### Environment

n/a

**Comment by coffee-cup** [comment]
That is a good idea! No reason that is not the case now.
