### ISSUE TITLE
Build doesn't work when an empty service is created and source files are uploaded using `railway up`

### ISSUE THREAD

**Issue by anilbhanushali** [railwayapp/nixpacks#385]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Build does not work when deployed using via cli using 'railway up' command

Here's the sample repo for [expressjs](https://github.com/anilbhanushali/expressjs) app which i used to tryout

### To reproduce

Scenarion 1
1. create an empty service under a project
2. deploy the source ( Docker or NodeJs project )using 'railway up'

Scenario 2
1. create a service by connecting your github repo
2. verify the deployment
3. clone the repo locally , make some minor changes to source and now deploy via cli using 'railway up'  command

### Expected behavior

- Application should run successfully and should be accessible via valid url
- Application logs should be visible in logs section

### Environment

- OS MacOS mojave version 10.14.6 (18G103)
- Railway cli version - 2.0.7
- Node version - v16.16.0
- Sample repo - https://github.com/anilbhanushali/expressjs

**Comment by coffee-cup** [comment]
I was just able to deploy the repo you linked with Nixpacks to Railway (https://build-no-work-express-production.up.railway.app).

This also seems like a Railway issue that you are experiencing, not a Nixpacks issue.

Can you please create a help thread in #project-help on the [Railway Discord Server](https://discord.gg/railway) with more information about the issue that you are seeing.
