### ISSUE TITLE
Add Dockerfile export

### ISSUE THREAD

**Issue by fuergaosi233** [railwayapp/nixpacks#419]
### Feature request

I would like to add an export for Dockerfile files.
It might look like this.
```
nixpacks generate . > Dockerfile
```

### Motivation

I'm using buildkit in my build system and I can't run docker build, so I want Nixpacks to generate the Dockerfile, and then I use the Dockerfile to build.

**Comment by coffee-cup** [comment]
This is already possible

You can either use `nixpacks build --out dir` to save what Nixpacks would build to the `dir` directory.

<img width="556" alt="image" src="https://user-images.githubusercontent.com/3044853/185445480-4a773a70-5b00-4a3d-9bca-b6812cd7ce2d.png">


Or you can use `nixpacks build --dockerfile` to simply log the contents of the `Dockerfile` to stdout.

<img width="661" alt="image" src="https://user-images.githubusercontent.com/3044853/185445361-6611029c-037c-4ef2-8525-2ef4fe79e764.png">

**Comment by fuergaosi233** [comment]
By the way Nixpack builds seem to be based on the nixpacks:debian package, which is not production friendly, would you consider using the alpine package?
