### ISSUE TITLE
Ruby: install libmysqlclient-dev when MySQL is detected

### ISSUE THREAD

**Issue by JakeCooper** [railwayapp/nixpacks#420]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

From this Discord thread

https://discord.com/channels/713503345364697088/1010103179544887376/1010103179544887376

If Rails has MySQL we need to install libmysqlclient-dev

### Environment

Current

**Comment by coffee-cup** [comment]
Related too https://github.com/railwayapp/nixpacks/issues/328
