### ISSUE TITLE
Fix csharp build

### ISSUE THREAD

**Issue by RicardoValero95** [railwayapp/nixpacks#424]
https://github.com/railwayapp/nixpacks/blob/dcc219ff9e3a09ee8e0fb7b45bf24b41e601bd0f/docs/pages/docs/providers/csharp.md?plain=1#L18

```
dotnet publish --no-restore -c Release -o out
```

**Comment by nebulatgs** [comment]
could you elaborate on what needs to be fixed?

**Comment by RicardoValero95** [comment]
Shouldn't the folder be called `out` instead of `{}`?

**Comment by RicardoValero95** [comment]
Sorry, maybe I'm wrong but can `ARTIFACT_DIR` be modified? or is it always "out"?

https://github.com/railwayapp/nixpacks/blob/cc2aa3384fa942678be6253f625c8d8990b83ad3/src/providers/csharp.rs#L29-L32

**Comment by JakeCooper** [comment]
> Sorry, maybe I'm wrong but can `ARTIFACT_DIR` be modified? or is it always "out"?
> 
> https://github.com/railwayapp/nixpacks/blob/cc2aa3384fa942678be6253f625c8d8990b83ad3/src/providers/csharp.rs#L29-L32

If you wanna create a PR for that envvar we would accept it

**Comment by JakeCooper** [comment]
Also please update the title to something more accurate and we can re-open this issue
