### ISSUE TITLE
Various path-related errors on Windows

### ISSUE THREAD

**Issue by nebulatgs** [railwayapp/nixpacks#433]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Things break on Windows because nobody bothered to test for it.

### To reproduce

`cargo test` 

### Expected behavior

it works :)

### Environment

Windows lol

**Comment by coffee-cup** [comment]
Can you please share the actual bugs/errors that occur. The main environment that Nixpacks is used in is Linux and unix-like system, which is why Windows compatibility has not been a priority. I am happy to accept PRs that improve Windows support, but issues that have no error messages or examples are not very useful.

**Comment by nebulatgs** [comment]
> Can you please share the actual bugs/errors that occur. The main environment that Nixpacks is used in is Linux and unix-like system, which is why Windows compatibility has not been a priority. I am happy to accept PRs that improve Windows support, but issues that have no error messages or examples are not very useful.

They all fail immediately since Windows paths are for example `C:\\Users\\Nebula\\whatever` while Unix paths are delimited with `/`, like `/home/nebula/whatever`. Converting a Windows path to a Unix path results in the `\\` delimiters being removed (the path would become `C:UsersNebulawhatever`.

This means every test fails.

**Comment by nebulatgs** [comment]
There are further errors due to Windows using `CRLF` line-endings, which Unix doesn't handle, causing the `cowsay` test, for example, to fail due to the rogue `\r` character.
