### ISSUE TITLE
.htaccess not working

### ISSUE THREAD

**Issue by MicroBotCodes** [railwayapp/nixpacks#442]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I was trying to run my website on railway and when I made a .htaccess file I tried to make the 404-page work in so many ways and it would not work.

### To reproduce

in .htaccess file: ErrorDocument 404 /404.html

when going to /asfiuahsdabskhbfb

![image](https://user-images.githubusercontent.com/69372160/186770711-f607df66-f653-484a-b830-f3a57986b7bd.png)

### Expected behavior

I would like it to show my 404 page.

### Environment

Nixpacks v0.3.7

**Comment by coffee-cup** [comment]
What language/provider are you using?

Nixpacks does not have any custom server and simply runs the start command of the app.

**Comment by nebulatgs** [comment]
`.htaccess` is for Apache, this is Nginx

**Comment by coffee-cup** [comment]
Nixpacks also only uses Nginx for PHP. Is this the PHP provider?

**Comment by coffee-cup** [comment]
Closing this as it is something we are unlikely to add support for in Nixpacks itself. Support for `.htaccess` (or similar) can be added at the application level.
