### ISSUE TITLE
Support for webpack in Rails projects

### ISSUE THREAD

**Issue by tsbarnes** [railwayapp/nixpacks#447]
### Feature request

Adding Webpack to the buildpack would be awesome

### Motivation

I'm trying to deploy a project using Rails and Webpack, but it fails with
```
Command "webpack" not found
```

**Comment by coffee-cup** [comment]
Do you have a `package.json` file with `"webpack"` as a dependency? Railway simple installs all the deps that are found there.

**Comment by coffee-cup** [comment]
Please share an example repo so we can reproduce the issue.

**Comment by tsbarnes** [comment]
Yes, the `package.json` includes `webpack` and `webpack-cli`. The project I'm trying to deploy is:
https://github.com/tsbarnes/tsbarnes-rails
