### ISSUE TITLE
Make devcontainer install gh

### ISSUE THREAD

**Issue by Milo123459** [railwayapp/nixpacks#459]
CC @devtomio

**Comment by Milo123459** [comment]
Yup

**Comment by devtomio** [comment]
alr ill work on this

**Comment by coffee-cup** [comment]
Can you please provide more information on why this should be added.

**Comment by Milo123459** [comment]
The GH CLI is really useful and can automate a lot of tasks

**Comment by coffee-cup** [comment]
Ah I just realized that this is not meant to be added to the base image and instead the GH devcontainer. That makes sense then.
