### ISSUE TITLE
Support Pandas/Numpy

### ISSUE THREAD

**Issue by JakeCooper** [railwayapp/nixpacks#462]
### Feature request

Various errors seem to occur with Pandas/Numpy, related to the following error

`ImportError: libstdc++.so.6: cannot open shared object file: No such file or directory`

Related Threads: 
- Discord: [here](https://discord.com/channels/713503345364697088/1013124535949733898/1013555831758917693)
- Twitter: [here](https://twitter.com/somil_agr/status/1563392838418976771)

It appears, going off this [nix forums post](https://discourse.nixos.org/t/python-package-with-runtime-dependencies/5522/7) we need to set the LD_LIBRARY. 

We already do this in Nixpacks ([here](https://github.com/railwayapp/nixpacks/blob/c51d381854dda521a45c2d0ddfca0f36f581d9a8/src/nixpacks/nix/mod.rs#L58)), probably need to make this more configurable or set-able on the provider level

If someone has a repo example that would be great, and would obviously love to take a PR for this

**Comment by coffee-cup** [comment]
Hmm we do already have custom support for numpy. I guess needs to be updated. https://github.com/railwayapp/nixpacks/blob/main/src/providers/python.rs#L107

**Comment by coffee-cup** [comment]
Perhaps the detection is slightly off

**Comment by Entropy5** [comment]
Just tested a pandas repo again and it still crashes with this error 
https://github.com/Entropy5/plotly-test

**Comment by coffee-cup** [comment]
I was just able to build and run that repo

<img width="1288" alt="image" src="https://user-images.githubusercontent.com/3044853/187341820-3ae026ff-2e59-4d9c-85c6-a158bb52b6e6.png">

What version of Nixpacks do you see an error with? And can you please share the full build logs (including build plan)

**Comment by coffee-cup** [comment]
Should be fixed in the latest version of nixpacks

**Comment by Entropy5** [comment]
I was using the railway browser implementation to deploy this straight from github with all default settings
I will try the commandline thing now

**Comment by AndreyBoyarchuk** [comment]
#10 9.670 ERROR: Could not find a version that satisfies the requirement numpy==1.25.2 (from versions: 1.3.0, 1.4.1, 1.5.0, 1.5.1, 1.6.0, 1.6.1, 1.6.2, 1.7.0, 1.7.1, 1.7.2, 1.8.0, 1.8.1, 1.8.2, 1.9.0, 1.9.1, 1.9.2, 1.9.3, 1.10.0.post2, 1.10.1, 1.10.2, 1.10.4, 1.11.0, 1.11.1, 1.11.2, 1.11.3, 1.12.0, 1.12.1, 1.13.0, 1.13.1, 1.13.3, 1.14.0, 1.14.1, 1.14.2, 1.14.3, 1.14.4, 1.14.5, 1.14.6, 1.15.0, 1.15.1, 1.15.2, 1.15.3, 1.15.4, 1.16.0, 1.16.1, 1.16.2, 1.16.3, 1.16.4, 1.16.5, 1.16.6, 1.17.0, 1.17.1, 1.17.2, 1.17.3, 1.17.4, 1.17.5, 1.18.0, 1.18.1, 1.18.2, 1.18.3, 1.18.4, 1.18.5, 1.19.0, 1.19.1, 1.19.2, 1.19.3, 1.19.4, 1.19.5, 1.20.0, 1.20.1, 1.20.2, 1.20.3, 1.21.0, 1.21.1, 1.21.2, 1.21.3, 1.21.4, 1.21.5, 1.21.6, 1.22.0, 1.22.1, 1.22.2, 1.22.3, 1.22.4, 1.23.0rc1, 1.23.0rc2, 1.23.0rc3, 1.23.0, 1.23.1, 1.23.2, 1.23.3, 1.23.4, 1.23.5, 1.24.0rc1, 1.24.0rc2, 1.24.0, 1.24.1, 1.24.2, 1.24.3, 1.24.4)

 

#10 9.670 ERROR: No matching distribution found for numpy==1.25.2

**Comment by aleksrutins** [comment]
> #10 9.670 ERROR: No matching distribution found for numpy==1.25.2

That looks like an issue with your Python version; have to tried updating to the latest (3.11) as described [here](https://nixpacks.com/docs/providers/python#setup)?
