### ISSUE TITLE
RFC: Build Plan Format

### ISSUE THREAD

**Issue by coffee-cup** [railwayapp/nixpacks#47]
As more and more features have been added to Nixpacks, the build plan has slowly evolved. Before it gets out of control, we should settle on a finalized build plan format that is human readable and intuitive.

The current build plan can be seen in the following screenshot

![image](https://user-images.githubusercontent.com/3044853/163489190-1c6c76d9-df81-414f-9809-d8f1d771ce9f.png)

I propose we flatten and simplify the format.

```ts
interface NixPackage {
  name: string;
  overlay?: string;
}

interface SetupPhase {
  nixPkgs: NixPackage[];
  onlyIncludeFiles?: string[];
}

interface InstallPhase {
  cmd?: string;
  onlyIncludeFiles?: string[];
}

interface BuildPhase {
  cmd?: string;
  onlyIncludeFiles?: string[];
}

interface StartPhase {
  cmd?: string;
}

interface BuildPlan {
  setup?: SetupPhase;
  install?: InstallPhase;
  build?: BuildPhase;
  start: StartPhase;
  variables: Record<string, string>;
}
```

Example: Yarn fastify

```json
{
  "setup": {
    "nixPkgs": [{ "name": "pkgs.stdenv" }, { "name": "pkgs.yarn" }]
  },
  "install": {
    "cmd": "yarn install --frozen-lockfile",
    "onlyIncludeFiles": ["package.json", "yarn.lock"]
  },
  "build": {
    "cmd": "yarn build"
  },
  "start": {
    "cmd": "yarn start"
  },
  "variables": {
    "NPM_CONFIG_PRODUCTION": "false",
    "NODE_ENV": "production"
  }
}
```

Example: Rust rocket

```json
{
  "setup": {
    "nixPkgs": [
      { "name": "gcc" },
      {
        "name": "(rust-bin.fromRustupToolchainFile ./rust-toolchain.toml)",
        "overlay": "https://github.com/oxalica/rust-overlay/archive/master.tar.gz"
      }
    ],
  "onlyIncludeFiles": ["rust-toolchain.toml"]
  },
  "build": {
    "dependsOn": "setup",
    "cmd": "cargo build --release",
    "onlyIncludeFiles": ["Cargo.toml"]
  },
  "start": {
    "cmd": "./target/release/rocket",
    "image": "alpine"
  },
  "variables": {
    "ROCKET_ADDRESS": "0.0.0.0"
  }
}
```

**Comment by wyzlle** [comment]
This looks good so far. How about adding optional post-install/pre-build and post-build/pre-deploy phases? Stuffs like database migration can be handled here.

**Comment by coffee-cup** [comment]
Thats a good idea. We could even handle it like node does. Look for and run `pre{NAME}` and `post{NAME}` scripts when running the `NAME` script. Def taking [Dagger](https://docs.dagger.io/1202/plan/) as inspiration and it would be cool if we could support arbitrary _phases_ with phase dependencies in the future.

**Comment by wyzlle** [comment]
How about adding `version` in `nixPkgs`? Considering that everyone isn't familiar with nix and finding nix revision for a specific version isn't easy. We'll have to maintain something like [nix-package-version](https://lazamar.co.uk/nix-versions).

**Comment by coffee-cup** [comment]
We've looked into this a bit before. I think that will be a thing we can have optional and add eventually. The support for a specific version (using something like nix-package-version) is a slightly separate discussion though.
