### ISSUE TITLE
Support MySQL autodetect with Django/Python

### ISSUE THREAD

**Issue by JakeCooper** [railwayapp/nixpacks#483]
### Feature request

Need to add auto detection of mysql client for Django

Related thread on Discord [here](https://discord.com/channels/713503345364697088/1014002182196043846/1014195641590751362)

### Contribution

If someone could give an example repo of this failing that would be a great start

**Comment by MCole-K9** [comment]
Here is the  example repo - https://github.com/MCole-K9/Django-Railway. 

Project ID:
ec74eabd-8f3b-4e44-b405-8bfbcf517af6.
