### ISSUE TITLE
.git not available in container

### ISSUE THREAD

**Issue by bogdan2510** [railwayapp/nixpacks#490]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I try to deploy a monorepo done with nx.dev. When i deploy to railway  trying to so some fancy nx.dev stuff i get this error:
`fatal: not a git repository (or any of the parent directories): .git`

`It appers that .git is not synced to the docker container.`

More logs [here](https://railway.app/project/aee320d8-15ae-49e8-84be-f336b5d9fc30/service/1ea4e910-d135-4c47-b09d-44b4a5042f4f?id=3a650f2c-1188-415c-8994-c83ab8477698)

### To reproduce

1. create a monorepo using nx.dev
2. create a bash script that is using this nx cmd : `nx print-affected`
3. Overwrite `NIXPACKS_BUILD_CMD ` to run the bash script

### Expected behavior

To be able to run `nx print-affected` successfully 

### Environment

- Macos latest version.
- Nixpacks latest version

**Comment by coffee-cup** [comment]
This is an issue with Railway, not with Nixpacks. Going to close here but please raise an issue in the [Railway discord](https://discord.gg/railway) #help channel.
