### ISSUE TITLE
Add MacPorts to install methods

### ISSUE THREAD

**Issue by Ci7rix** [railwayapp/nixpacks#493]
### Feature request

I added nixpacks to MacPorts (https://github.com/macports/macports-ports/pull/15967).
Can I create a pull request to add this method to the documentation ?

### Motivation

Some people don't use Homebrew but MacPorts instead.

### Contribution

I already forked the repo and pushed the MacPorts install method (7c513cdeea04a3ae7ccb0fd4eeb61c2899a8a5aa)

**Comment by devtomio** [comment]
sure, your pr is much appreciated

**Comment by Ci7rix** [comment]
Thanks ! Here is it : https://github.com/railwayapp/nixpacks/pull/495
