### ISSUE TITLE
Allow specifying nixpacks config in Cargo.toml package.metadata section

### ISSUE THREAD

**Issue by lilyball** [railwayapp/nixpacks#494]
### Feature request

When building a Rust project, it would be really handy if I could add a `[package.metadata.nixpacks]` section to my `Cargo.toml` and use that to specify things like libs, apt, pkgs, etc. This way the project specifies its dependencies and can be built directly with `nixpacks` without having to pass separate env vars or flags.

This is a Rust-specific solution, and maybe it's better to pursue a language-independent one such as reading an `.env` file for the `NIXPACKS_*` env vars, or letting me define a `nixpacks.nix` file that's a nix module that provides definitions for config keys (e.g. a file containing `{ pkgs, ... }: { pkgs = [ pkgs.jq ]; }`), but the Rust solution is pretty straightforward and could be reproduced in any language that supports structured metadata in package info.

### Motivation

This would really help right now because I'm trying to use `flyctl deploy --nixpacks` and I can't find any way to pass nixpacks configuration via `flyctl`. That is undoubtedly something that `flyctl` should support, but a solution on the nixpacks side would make it easier for wrapper tools (like `flyctl`) to work.

### Contribution

Sorry

**Comment by JakeCooper** [comment]
We're chatting a bit about this internally, and it also came up in the CLI repo as well

https://github.com/railwayapp/cli/issues/263

We'd love to work on an actual IaC representation. We've fiddled with it internally, but I'd like to start tracking requirements/demand externally as well

https://feedback.railway.app/feature-requests/p/infrastructure-as-code

**Comment by IgnisDa** [comment]
I suggest we introduce a `nixpacks.toml` which can allow to allow these configurations.

**Comment by coffee-cup** [comment]
> I suggest we introduce a `nixpacks.toml` which can allow these configurations.

I have an RFC coming for this soon 🙂
