### ISSUE TITLE
Spring Boot Application Fails to Build Correctly

### ISSUE THREAD

**Issue by erkihindo** [railwayapp/nixpacks#504]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Tried to build my simple Java 8 Spring Boot service in Railway.

With Nixpacks, it doesn't work. 
With Heroku Buildpacks, it works just fine.

Example repo:
https://github.com/erkihindo/random-repo

With Nixpacks:
![error](https://user-images.githubusercontent.com/16940944/188684243-ef321107-8132-411c-9362-ff956d1fe8e3.png)

With Heroku buildpack:
![heroku_one_works_fine](https://user-images.githubusercontent.com/16940944/188684244-b6cd4aca-9579-41ad-99e8-097e4631eab9.png)

### To reproduce

Try and run the app on Railway.

### Expected behavior

Expected - for Nixpacks to run as smoothly as Heroku buildpacks

### Environment

Java 8 Spring Boot.

**Comment by Milo123459** [comment]
As of right now, I don't think we support Gradle.

**Comment by russellbanks** [comment]
> As of right now, I don't think we support Gradle.

Isn't Gradle supported under https://nixpacks.com/docs/providers/java?

**Comment by Milo123459** [comment]
I implemented support for it yesterday. Anyway, @erkihindo could you try deploying on Railway again? Are you still experiencing this issue?

**Comment by erkihindo** [comment]
@Milo123459 
This is what I get now:
<img width="1625" alt="Screenshot at Sept 09 08-05-41" src="https://user-images.githubusercontent.com/16940944/189275681-853d6822-664c-43b3-ac6d-35b12e99fe54.png">


`#11 3.774
#11 3.774 Welcome to Gradle 6.7.1!
#11 3.774
 
#11 3.774 Here are the highlights of this release:
#11 3.774  - File system watching is ready for production use
#11 3.774  - Declare the version of Java your build requires
#11 3.774  - Java 15 support
#11 3.774
#11 3.775 For more details see https://docs.gradle.org/6.7.1/release-notes.html
#11 3.775
#11 3.873 Starting a Gradle Daemon (subsequent builds will be faster)
 
#11 6.073
#11 6.073 FAILURE: Build failed with an exception.
#11 6.073
#11 6.073 * Where:
#11 6.073 Settings file '/app/settings.gradle'
#11 6.073
#11 6.073 * What went wrong:
#11 6.073 Could not compile settings file '/app/settings.gradle'.
#11 6.073 > startup failed:
#11 6.073   General error during semantic analysis: Unsupported class file major version 61
#11 6.073
#11 6.073   java.lang.IllegalArgumentException: Unsupported class file major version 61
#11 6.073   	at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:196)
#11 6.073   	at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:177)
#11 6.073   	at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:163)
#11 6.074   	at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:284)
#11 6.074   	at org.codehaus.groovy.ast.decompiled.AsmDecompiler.parseClass(AsmDecompiler.java:81)
#11 6.074   	at org.codehaus.groovy.control.ClassNodeResolver.findDecompiled(ClassNodeResolver.java:251)
#11 6.074   	at org.codehaus.groovy.control.ClassNodeResolver.tryAsLoaderClassOrScript(ClassNodeResolver.java:189)
#11 6.074   	at org.codehaus.groovy.control.ClassNodeResolver.findClassNode(ClassNodeResolver.java:169)
#11 6.074   	at org.codehaus.groovy.control.ClassNodeResolver.resolveName(ClassNodeResolver.java:125)
#11 6.074   	at org.codehaus.groovy.ast.decompiled.AsmReferenceResolver.resolveClassNullable(AsmReferenceResolver.java:57)
#11 6.074   	at org.codehaus.groovy.ast.decompiled.AsmReferenceResolver.resolveClass(AsmReferenceResolver.java:44)
#11 6.074   	at org.codehaus.groovy.ast.decompiled.AsmReferenceResolver.resolveNonArrayType(AsmReferenceResolver.java:79)
#11 6.074   	at org.codehaus.groovy.ast.decompiled.AsmReferenceResolver.resolveType(AsmReferenceResolver.java:70)
#11 6.074   	at org.codehaus.groovy.ast.decompiled.MemberSignatureParser.createMethodNode(MemberSignatureParser.java:57)
#11 6.074   	at org.codehaus.groovy.ast.decompiled.DecompiledClassNode$2.get(DecompiledClassNode.java:234)
#11 6.074   	at org.codehaus.groovy.ast.decompiled.DecompiledClassNode$2.get(DecompiledClassNode.java:231)

...`

**Comment by erkihindo** [comment]
😮 It is now working

**Comment by Milo123459** [comment]
Fantastic!
