### ISSUE TITLE
NX Provider: Support apps in non-standard locations

### ISSUE THREAD

**Issue by coffee-cup** [railwayapp/nixpacks#566]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The NX provider will error if the NX apps are not in the standard `app/` directory. Instead of assuming that this directory exists, we should use `workspace.json` as a way to find the app root.

We should also provide a way to opt of of the behaviour provided by the NX provider so that users can get around errors like this.

### Environment

Nixpacks 0.5.3

**Comment by Milo123459** [comment]
Do you know how we detect it? https://nx.dev/deprecated/workspace-json doesn't give a whole lot of information.

**Comment by coffee-cup** [comment]
Hmm not sure actually. I wasn't aware that `workspace.json` was deprecated. I think we can still use it if it exists to support repos that are setup that way.

**Comment by coffee-cup** [comment]
Any update on this @Milo123459 ? I'm happy to take it if you haven't started yet.
