### ISSUE TITLE
PHP: Build doesn't work with `ext-libxml` dependency

### ISSUE THREAD

**Issue by MidnightDesign** [railwayapp/nixpacks#569]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Running `nixpacks build` in a PHP project with the Composer dependency `ext-libxml` errors out.

### To reproduce

1. Create a `composer.json` file with the following contents in an empty directory:
```json
{"require": {"ext-libxml": "*"}}
```
2. Run `nixpacks build . --name test` from that directory
3. The following error appears:
```
=> ERROR [5/8] RUN nix-env -if .nixpacks/setup.nix && nix-collect-garbage -d                                                                                                     16.0s 
------
 > [5/8] RUN nix-env -if .nixpacks/setup.nix && nix-collect-garbage -d:
#9 13.65 installing 'setup-env'
#9 14.53 error: attribute 'libxml' missing
#9 14.53
#9 14.53        at /app/.nixpacks/setup.nix:19:49:
#9 14.53
#9 14.53            18|         '')
#9 14.53            19|         php81 perl nginx php81Packages.composer php81Extensions.libxml
#9 14.53              |                                                 ^
#9 14.53            20|       ];
#9 14.53 (use '--show-trace' to show detailed location information)
------
executor failed running [/bin/bash -ol pipefail -c nix-env -if .nixpacks/setup.nix && nix-collect-garbage -d]: exit code: 1
Error: Docker build failed
```

### Expected behavior

The build runs successfully.

### Environment

Windows 11, nixpacks 0.5.9

**Comment by nebulatgs** [comment]
It should be `ext-xml`, not `ext-libxml`

**Comment by MidnightDesign** [comment]
You're right, it does work with `ext-xml`. I wonder what `ext-libxml` is about then, because if it was invalid, Composer would complain about it:

```
Loading composer repositories with package information
Updating dependencies                                 
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires PHP extension ext-foo * but it is missing from your system. Install or enable PHP's foo extension.
```

Maybe it's some kind of alias for `ext-xml`? In that case, Nixpacks should probably treat it like that as well.

**Comment by coffee-cup** [comment]
Nixpacks installs the PHP packages before composer is even run and gets a chance to complain.

In any case, I am going to close this since the main issue is solve/not a nixpacks issue.
