### ISSUE TITLE
Support OpenSSL 3

### ISSUE THREAD

**Issue by coffee-cup** [railwayapp/nixpacks#574]
In the latest version of the Nix unstable channel, openssl version 3 is the default instead of version. This breaks a few of our examples that depend on openssl 1 (e.g. node prisma). For now, the nixpkgs archive can be pinned to an older version, but we should do a few things to improve how Nixpacks handles openssl.

- Improved clarity around where openssl comes from. Our base debian image installs openssl with apt-get. However, this version can conflict with openssl from nixpkgs
- Allow users to specify which version of openssl they want. If version 1 is specified, this version should be used for all Nix packages that get installed

https://github.com/NixOS/nixpkgs/compare/a0b7e70db7a55088d3de0cc370a59f9fbcc906c3...8a5b9ee7b7a2b38267c9481f5c629c015108ab0d

**Comment by Milo123459** [comment]
What if we just don't install OpenSSL via apt?

**Comment by coffee-cup** [comment]
> What if we just don't install OpenSSL via apt? That would remove the conflicts and would be easier for this to work, right?

I tried a few things like that and was unable to get prisma to install and work correctly. Although happy to be proven wrong here.

**Comment by mabadir** [comment]
I have hit the same issue, even removing openSSL from apt, I still had the same issue.

**Comment by Milo123459** [comment]
Are there any new ideas on how we can do this? Really wanna get this supported.

**Comment by coffee-cup** [comment]
Hey, apologizes for the late reply on this (I need to get my GitHub notifications sorted out). 

> I am not sure what changed that made Prisma to work again.

We are now pinning an older version of the Nix archive where the default version of OpenSSL is 2. This is not ideal and prevents us from easily upgrading.

Prisma should support openssl 3 now (https://github.com/prisma/prisma/issues/11356) but I've still seen some issues with Nixpacks. That may be because openssl is being installed with Apt and conflicting with the Nix version.

It would also be good if we could fallback to openssl 2 for apps that need it. The Prisma example in the repo is a good test case if anyone wants to pick this up https://github.com/railwayapp/nixpacks/tree/main/examples/node-prisma-postgres
