### ISSUE TITLE
Support MySQL for PHP Laravel apps

### ISSUE THREAD

**Issue by jplhomer** [railwayapp/nixpacks#610]
### Feature request

It would be sweet if Nixpacks could automatically install the `default-mysql-client` apt package when a Laravel/PHP app is detected.

### Motivation

Currently, in order to get my Laravel app to connect to the MySQL database on Railway, I have to inject a variable `NIXPACKS_APT_PKGS=default-mysql-client`. Otherwise, when running `php artisan db:migrate --force` during build, I get a `command not found: mysql` error.

I'd imagine this would be similar to #431 - though it's unfortunate Laravel doesn't offer a great way to detect the database adapter in use. 

Would it be bad to default to installing it for every PHP app? IMO the vast majority of PHP apps will be connecting to MySQL (given the history of WordPress, etc etc). The downside here would be image size, of course.

### Contribution

Happy to contribute this as a PR if given the 👍

**Comment by aleksrutins** [comment]
Honestly, the image size increase would probably be insignificant - it probably would be a good idea to just install it for all PHP apps.
