### ISSUE TITLE
Automatically cache `.tsbuildinfo` files for Typescript usage

### ISSUE THREAD

**Issue by flybayer** [railwayapp/nixpacks#626]
### Feature request

When tsconfig `incremental` is enabled (recommended by TS team for all projects the last I knew), the `.tsbuildinfo` cache file makes a massive improvement in build speed.

Most people probably use the default  `.tsbuildinfo`, although to be extra smart we could parse tsconfig and look for `tsBuildInfoFile` setting. Although I'm not sure this part is worth the effort.

**Comment by FinnDore** [comment]
This looks promising at first glance https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-4.html

About the location of this file. For normal projects im guessing this will be at `/dist/.tsbuildinfo` for a next project it seems like this file is located at `.next/cache/.tsbuildinfo` [which is fine cus we cache the whole of](https://github.com/railwayapp/nixpacks/blob/main/src/providers/node/mod.rs#L341) `.next/cache`.

Could we search for `**.tsbuildinfo' and just cache the first or all of the matches.

Side note, does anyone know of a big project i can use for per comparisons?

**Comment by coffee-cup** [comment]
I think the `.tsbuildinfo` file is located at the root of the project (beside `tsconfig.json`). In that case we could look for all ts config files and cache tsbuildinfo files along side it.

> Could we search for `**.tsbuildinfo' and just cache the first or all of the matches.

Unfortunately, the files/directories to be cached must be decided ahead of the actual build that generates the files.

**Comment by Milo123459** [comment]
I've made a PR for this: #734.
