### ISSUE TITLE
Nixpacks Bug Report

### ISSUE THREAD

**Issue by MattiaVerticchio** [railwayapp/nixpacks#640]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hi!
I’m trying to deploy on Railway using Nixpacks and Bun, however when running `bun install` or `bun upgrade` I get the following error.

```
error: memlock limit exceeded

To fix this error: please increase the memlock limit or upgrade to Linux kernel 5.11+

If Bun is running inside Docker, make sure to set the memlock limit to unlimited (-1)

docker run --rm --init --ulimit memlock=-1:-1 jarredsumner/bun:edge
```

How can I set the last line as an option in Nixpacks?
Thanks!

### Environment

```toml
[phases.setup]
nixPkgs = ['nodejs', 'yarn', 'bun']

[phases.build]
cmds = ['bun upgrade', 'yarn install', 'yarn run build-backend', 'cd backend', 'bun install']

[start]
cmd = 'bun run backend/index.ts'
```

**Comment by coffee-cup** [comment]
This depends on the host that Nixpacks is building on (in this case Railway). There is nothing that Nixpacks can do in this case.
