### ISSUE TITLE
PHP app not working

### ISSUE THREAD

**Issue by divineniiquaye** [railwayapp/nixpacks#652]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I tried running a website yesterday on Railway and was unsuccessful. I thought it was a problem with my app, so I tried deploying the railway's laravel template, it deployed successfully but got error 500 on the webpage.

I deleted the `.htaccess` file from the root path and got an error `403` after re-deployment. The website source code is at https://github.com/biurad/flange-demo

### Expected behavior

I did further investigation and suggest two important changes which will use an env `ROOT_PATH` or named anything else with default value `/app`. This will allow PHP projects to change where their application needs to start.

The first change should be in the [nginx.template.conf]( https://github.com/railwayapp/nixpacks/blob/1f8b0aedcd6123c936ea407ffb8e133a50150153/src/providers/php/nginx.template.conf#L29) file

```diff
- $if(IS_LARAVEL) (
-     root /app/public;
- ) else (
-     root /app;
- )
+ root ${ROOT_PATH};
```

The next change in the same `nginx.template.conf` file, should be:

```diff
- $if(IS_LARAVEL) (
-     location / {
-         try_files $uri $uri/ /index.php?$query_string;
-     }
- ) else ()
+ location / {
+     try_files $uri $uri/ /index.php?$query_string;
+ }
```

A temporary solution is to an env of `IS_LARAVEL=yes` if your application processes requests from project's root `/public` directory.

### Environment

```plain
╔══════════════════════════════ Nixpacks v0.12.1 ══════════════════════════════╗
║ setup      │ php80, perl, nginx, php80Packages.composer,                     ║
║            │ php80Extensions.pdo_sqlite, nodejs-16_x, npm-8_x                ║
║──────────────────────────────────────────────────────────────────────────────║
║ install    │ mkdir -p /var/log/nginx && mkdir -p /var/cache/nginx            ║
║            │ composer install                                                ║
║            │ npm i                                                           ║
║──────────────────────────────────────────────────────────────────────────────║
║ build      │ npm run build                                                   ║
║──────────────────────────────────────────────────────────────────────────────║
║ start      │ ([ -e /app/storage ] && chmod -R ugo+w /app/storage); perl      ║
║            │ /assets/transform-config.pl /assets/nginx.template.conf         ║
║            │ /nginx.conf && echo "Server starting on port $PORT" && (php-fpm ║
║            │ -y /assets/php-fpm.conf & nginx -c /nginx.conf)                 ║
╚══════════════════════════════════════════════════════════════════════════════╝
```

>No environmental variables was used for my application except the default.

**Comment by divineniiquaye** [comment]
I was able to get the URL working properly by setting `IS_LARAVEL` env and it's value to `yes` but faced a new problem. It seems my storage directory which is named `var` has permission restrictions.

@coffee-cup I kindly need your help to resolve this issue. I tried setting the `NIXPACKS_BUILD_CMD` env with value `npm run build && php -r "chmod('/app/var/', 0755);"` and it did not work, I previously I used `chmod -R a+rX /app/var` and `chmod 755 /app/var -R` it still didn't work. 

You can check out the issue from the my webpage: https://flange-blog-demo.up.railway.app/

**Comment by divineniiquaye** [comment]
I am closing this issue now since it wasn't attended to, I was able to fix the problem by switching from `Nixpacks` to `Heroku Buildpacks`.

My website required write access to `/tmp` and `/app/var` directory, since I wasn't able quite figure out how to solve this problem upon several tries I decided to close this issue.

**Comment by coffee-cup** [comment]
Hi @divineniiquaye, Apologizes that we were not able to respond on this issue right away. It has been a really busy week for the team.

I've re-opened this issue since it hasn't been resolved in Nixpacks yet and is indeed a bug.

For quicker more immediate help with Railway and builds please use the #help channel in [Discord](https://discord.gg/railway).
