### ISSUE TITLE
Ruby image keeps rvm source, bloating the image by 600MB

### ISSUE THREAD

**Issue by jsierles** [railwayapp/nixpacks#653]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

After building a stock Rails app with the Ruby provider, I noticed the resulting image is 1.2GB!

I found that RVM keeps its source install around, which weighs around 600MB. I suspect that cleaning this up during the install phase will shrink the image.

```
root@580142ed:/usr/local/rvm/src# du -sh .
633M	.
root@580142ed:/usr/local/rvm/src# ls
ruby-3.1.2  rvm
```

### To reproduce

Run `nixpacks build .` on a stock Rails app and examine the resulting image contents.

### Environment

nixpacks 0.2.11 on MacOS 13.0

**Comment by coffee-cup** [comment]
Yes the Ruby images are very large :/
Would love to clean these up as much as possible. Good suggestion on removing the rvm src!

**Comment by jsierles** [comment]
I'd also consider switching to another release manager that caches binaries for common Ruby versions, like [rbenv](https://github.com/rbenv/rbenv). That will speed up the initial build.

**Comment by coffee-cup** [comment]
Yes agreed there too. It is not as simple as just flipping a switch so likely won't be added until later next week. In the meantime I've pushed a simple fix to remove the rvm source after Ruby installation.

**Comment by coffee-cup** [comment]
Thanks! Really appreciate it.
The team here doesn't have a ton of experience with Ruby so I'm sure there are things Nixpacks could be doing better 😄
