### ISSUE TITLE
no main manifest attribute error on running spring boot service image built using nixpacks 

### ISSUE THREAD

**Issue by lcbasu** [railwayapp/nixpacks#677]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I am able to build a spring boot application using nixpacks and able to push the image to docker. But when I run the docker image I get `no main manifest attribute` error.

### To reproduce

1. Create a project with https://start.spring.io/ using Gradle.
2. Build it using `nixpacks build . --name "IMAGE_NAME"`
3. Push the image to docker.
4. Run the docker image
5. The image fails to run with `no main manifest attribute` error

### Expected behavior

The application should run at port 5000 with an active hello/world api endpoint.

### Environment

Linux EC2 VM

**Comment by lcbasu** [comment]
Solved it by removing the *-plain.jar from the build folder which started happening after version 2.5.

Add this to the Gradle file 

```
tasks.jar { enabled = false }
```

**Comment by coffee-cup** [comment]
Interesting issue. Nixpacks should work even if `*-plain.jar` is present in the build folder.
