### ISSUE TITLE
Ability to customize pnpm version

### ISSUE THREAD

**Issue by flybayer** [railwayapp/nixpacks#680]
### Feature request

Currently I don't see any way to customize the pnpm version that is installed. Pnpm has been known to have breaking changes in minor versions and sometimes you need more control, especially when using pnpm-patches.

**Workaround**

Manually install desired pnpm version in start of `install` command

**Comment by JakeCooper** [comment]
Yea there's an overaching theme with Nix where it's great for a lot of things because you essentially get a "slice" of all things together, but version specific attenuations will likely need to come in the form of custom phases

Very open to thoughts/ideas/etc here. It's top of mind for us and I know JR has thought a lot about this

**Comment by coffee-cup** [comment]
PNPM, Yarn, and NPM all come from our custom Nix overlay that auto updates with the latest version (the versions in nixpkgs were out of date).

https://github.com/railwayapp/nix-npm-overlay/blob/main/pkgs/pnpm-7_x/default.nix

We could pin to a specific commit of that repo to install a specific version of PNPM.

However, I think the better option would be to use [Corepack](https://pnpm.io/installation#using-corepack) to install versions of PNPM. Nixpacks is already getting support for it for Yarn 2+, but we could extend to all Node package managers.

I think you could already use it with a `nixpacks.toml` file that looks something like

```toml
[phases.install]
cmds = ["npm install -g corepack", "corepack enable", "corepack prepare pnpm@<version> --activate", "..."]
```

_Note: I haven't tested this_

**Comment by coffee-cup** [comment]
This is now possible as of version `0.16.0` of Nixpacks. Docs here https://nixpacks.com/docs/providers/node#corepack
