### ISSUE TITLE
If package manifest isn't found, don't do a clean install

### ISSUE THREAD

**Issue by Milo123459** [railwayapp/nixpacks#71]
This is causing issues because some people don't commit `yarn.lock` & `package-lock.json`. We need to remove `--frozen-lockfile` in Yarn if `yarn.lock` doesn't exist, and we need to do `npm i` instead of `npm ci` if `package-lock.json` doesn't exist.

**Comment by coffee-cup** [comment]
Fixed in https://github.com/railwayapp/nixpacks/pull/89
