### ISSUE TITLE
nixpacks.toml `VARIABLES` aren't read by providers

### ISSUE THREAD

**Issue by Milo123459** [railwayapp/nixpacks#722]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

a variable defined in nixpacks.toml "VARIABLES" section does not get read by providers.

### Environment

railway

**Comment by dwaynemac** [comment]
This happend to me too. 
`
[variables]
NIXPACKS_NODE_VERSION=14.18.2
`
is ignored on build.

Setting the variable on the service through railway's UI works fine.
