### ISSUE TITLE
Elixir provider

### ISSUE THREAD

**Issue by wyzlle** [railwayapp/nixpacks#75]

**Comment by wyzlle** [comment]
> Also should support phoenix and nerves projects

Yup.

[Buildpack](https://elements.heroku.com/search/buildpacks?q=elixir) behavior would be the ideal here. You can add more features on top of that if you want.

**Comment by jozsefsallai** [comment]
Hey! I've already kind of started working on this, but I don't think I have the time to finish it, so I wouldn't mind passing it over. Here's my changes, you may use that as a starting point if you'd like: https://github.com/jozsefsallai/nixpacks/commit/c9515ed454170b2a586beb350e6295f322c91349 (there's also a separate branch for this).

It should work for simple projects. I wanted to add support for escript binaries, but they will not start:
```
joe@ellsworth ~> docker run -it elixir
/usr/bin/env: 'escript': No such file or directory
```

Also haven't tested it with Phoenix, but it will likely need additional configuration/checks.

Ideally these should work as the Heroku buildpacks (for Elixir and Phoenix). There's a thread in the nixpacks channel on the Railway Discord if you have any questions.

**Comment by christhekeele** [comment]
Point of order: this was closed as completed, but the corresponding pull request was not merged, but instead shuttered, so this is arguably not completed.

**Comment by coffee-cup** [comment]
> Point of order: this was closed as completed, but the corresponding pull request was not merged, but instead shuttered, so this is arguably not completed.

New language/framework related issues were closed in favour of [this discussion item](https://github.com/railwayapp/nixpacks/discussions/245)

**Comment by christhekeele** [comment]
Got it, thanks!
