### ISSUE TITLE
Ruby: Rails build fails when configured as an api

### ISSUE THREAD

**Issue by taphill** [railwayapp/nixpacks#751]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I ran into a build failure when attempting to deploy a new Rails API to Railway using the `railway up` command.

It appears that the build fails when it tries to run this rake task `assets:precompile`

<img width="964" alt="Screen Shot 2023-01-03 at 7 10 01 PM" src="https://user-images.githubusercontent.com/62676321/210466360-cf2c254d-34c3-49c3-a3cf-19966b50d67c.png">

This is because when you create a rails project with the `--api` flag it skips all the views, assets, etc. as outlined in the Rails docs [here](https://guides.rubyonrails.org/api_app.html#the-basic-configuration), so the `assets:precompile` task does not exist.

[I think this is the function that probably needs to be updated](https://github.com/railwayapp/nixpacks/blob/main/src/providers/ruby.rs#L242)

It looks like you're looking within the `config/application.rb` file. Perhaps you can add some logic to look for the `config.api_only = true` line and adjust the build settings based on that.

<img width="779" alt="Screen Shot 2023-01-03 at 7 18 54 PM" src="https://user-images.githubusercontent.com/62676321/210467126-1880ebcf-b5e1-4dd8-b4cd-9a64c82c238d.png">

### To reproduce

1. In the Railway dashboard, create a new empty project
2. On your local machine, create a new rails API with a postgres db `rails new my_api --api --database=postgresql`
3. Create and migrate the db `rails db:{create,migrate}`
4. Back in the Railway dashboard click the button at the bottom to set up your project locally
5. Copy the Railway link to connect to the Railway project and paste it into your terminal
6. Run `railway up`

### Expected behavior

I would expect the build to succeed.

### Environment

MacOS 12.3.1
ruby 3.2.0
rails 7.0.4

<img width="768" alt="Screen Shot 2023-01-03 at 11 02 01 PM" src="https://user-images.githubusercontent.com/62676321/210487722-f1e80051-9231-4beb-9599-08bec3a02383.png">

**Comment by taphill** [comment]
I've not ever used Rust before, but on the surface, it seems like this would be a somewhat easy fix. I'd be happy to try and submit a PR if this is a feature you would want to support.

**Comment by fusion2004** [comment]
I think you can fix this in a `nixpacks.toml` config file:
```toml
[phases.build]
cmds = [] # remove this to re-enable asset building
```
