### ISSUE TITLE
Cannot Install libcairo2 During Build Of Nixpack

### ISSUE THREAD

**Issue by alvindera97** [railwayapp/nixpacks#769]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The following is the content of my **nixpacks.toml** file as I am building a django project that makes use of `cairocffi`. 

```
[phases.release]
aptPkgs = ["...", "libcairo2-dev"]
```

No matter where the command to install packages is placed i.e. **[phases.setup]** or **[phases.install]** or **[phases.release]**, I still get the error that:

```
OSError: no library called "cairo-2" was found
no library called "cairo" was found
no library called "libcairo-2" was found
cannot load library 'libcairo.so.2': libcairo.so.2: cannot open shared object file: No such file or directory
cannot load library 'libcairo.2.dylib': libcairo.2.dylib: cannot open shared object file: No such file or directory
cannot load library 'libcairo-2.dll': libcairo-2.dll: cannot open shared object file: No such file or directory
```

during `python manage.py migrate` at **phases.release]**

I encountered an error during the `python manage.py migrate` section because the save method of one of my models depends on a function that calls `cairocffi` somewhere down the call stack.

**In the reproduction section, you wouldn't have to go through creating models to execute in import call for `cairocffi`**

### To reproduce

- Install django via the command `python -m pip install Django`
- Create a django project and create a **nixpacks.toml** file on the project root. 
- Populate the content of **nixpacks.toml** with the file content (below these bullet points). 
- Create a python module (let's call this `recreate.py`) which should contain only one line inside there `import cairocffi`.
- Add **requirements.txt** to project root.
- Populate **requirements.txt** via the terminal command `python -m pip freeze > requirements.txt
- Append `gunicorn` on a new line just below the last line in the **requirements.txt** file
- Build the project using the command `sudo nixpacks build . --name recreate-app`
- After successful build ,run the command: `sudo docker run -it recreate-app bash`
- Execute the command `python recreate.py` and get the `OSError` raised.

Provide the following in your nixpacks.toml file
```
[phases.setup]
aptPkgs = ["...", "libcairo2"]
```

This is the exception raised:

```
OSError: no library called "cairo-2" was found
no library called "cairo" was found
no library called "libcairo-2" was found
cannot load library 'libcairo.so.2': libcairo.so.2: cannot open shared object file: No such file or directory
cannot load library 'libcairo.2.dylib': libcairo.2.dylib: cannot open shared object file: No such file or directory
cannot load library 'libcairo-2.dll': libcairo-2.dll: cannot open shared object file: No such file or directory
```

### Expected behavior

After `install` phase, a `build` phase is expected to run which it does. 
The build phase executes the command: 
```
python manage.py migrate
```

A `start phase` executes after the `release phase` and build should be successful.

### Environment

OS: **'Ubuntu 22.04.1LTS'**
Python Version: **'python-3.10'**
Nixpacks Version: **'1.1.1'**

**Comment by aleksrutins** [comment]
Try putting this in `phases.setup`, instead of using APT:
```toml
[phases.setup]
nixPkgs = ['...', 'cairo']
nixLibs = ['...', 'cairo']
```
