### ISSUE TITLE
Staticfile/HTML provider

### ISSUE THREAD

**Issue by wyzlle** [railwayapp/nixpacks#77]

**Comment by Milo123459** [comment]
How would this work?

**Comment by wyzlle** [comment]
Can detect using a specific variable/file (that provides more config options) or maybe if everything fails and it has `index.html` in root

**Comment by Milo123459** [comment]
I don't think this is a good idea. Setting up a web server isn't hard.

**Comment by wyzlle** [comment]
Some people find setting a production ready server difficult. Adding a variable is more easier than setting a web server.

**Comment by Milo123459** [comment]
If this is done, I don't think a variable is the right way to go about doing this. We should implement some sort of hierarchy for providers and this should have the lowest because it is way too generic.

**Comment by Milo123459** [comment]
What webserver would we use anyway?

**Comment by wyzlle** [comment]
> If this is done, I don't think a variable is the right way to go about doing this. We should implement some sort of hierarchy for providers and this should have the lowest because it is way too generic.

Variable because it's much easier. Hierarchy won't be the perfect solution in this case. Imagine a situation where someone deploys code written in a language which isn't supported by nixpacks, yet. That way one can get their source code leaked.

**Comment by wyzlle** [comment]
> What webserver would we use anyway?

I'd prefer Caddy/Nginx. If someone has a better suggestion. We can go ahead with that.

**Comment by JakeCooper** [comment]
Adding a $100 bounty for this provider (nginx serving, similar to the static buildpacks). Payable in crypto or USD.

**Comment by wyzlle** [comment]
I am up for this.

**Comment by Milo123459** [comment]
If we have settled on the idea of it being an environment variable, which upon second thought is a better idea, maybe we should have an option in the railway dashboard for deploying a static HTML application like this. Just a checkmark that would automatically set this variable.

**Comment by wyzlle** [comment]
Haven't settled on the idea of it being an environment variable. Will be rewriting Cloudfoundry's [Staticfile buildpack](https://docs.cloudfoundry.org/buildpacks/staticfile/) as a provider.
