### ISSUE TITLE
Build fails for Rust projects with more than one binary

### ISSUE THREAD

**Issue by m1guelpf** [railwayapp/nixpacks#779]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

If the compiled binary name doesn't match the name of the project, the cp command will fail and the build won't succeed.

see here:
https://github.com/railwayapp/nixpacks/blob/1c0e460cf3c98d352d506e3d9846f2df06273e4e/src/providers/rust.rs#L101-L104

### To reproduce

1. Make a Cargo project with more than one binary (for example, move `main.rs` to `bin/bin1.rs`, and duplicate it to `bin/bin2.rs`)
2. Attempt to build the project

### Expected behavior

All compiled binaries get copied over (or, alternatively, there's some way to select which binary to use).

### Environment

```
╔═══════════════════════════════ Nixpacks v1.1.1 ══════════════════════════════╗
║ setup      │ binutils, gcc, (rust-bin.stable.latest.default.override {       ║
║            │ targets = ["x86_64-unknown-linux-musl"]; }), musl, musl.dev     ║
║──────────────────────────────────────────────────────────────────────────────║
║ build      │ mkdir -p bin                                                    ║
║            │ cargo build --release --target x86_64-unknown-linux-musl        ║
║            │ cp target/x86_64-unknown-linux-musl/release/rust-test bin       ║
║──────────────────────────────────────────────────────────────────────────────║
║ start      │ ./bin/rust-test                                                 ║
╚══════════════════════════════════════════════════════════════════════════════╝
```

**Comment by ndneighbor** [comment]
Hey Miguel! Can you walk me a bit through the structure of your project and the goal of multiple bins within your project? We have an assumption that services on Railway are 1:1 to the build artifacts that get added on. (FlightControl + others might have different assumptions.) 

Also going to tag in @nebulatgs who might have an opinion on how we should be looking at this.

**Comment by m1guelpf** [comment]
@ndneighbor I have a project that exposes both an API and a CLI, and since there's little difference between these two they are on the same project. I _guess_ I could use workspaces for this (haven't looked into that yet), but this felt like it would work.

**Comment by coffee-cup** [comment]
This should indeed be a supported flow! How would you expect to indicate which binary should be run by default when the app starts?

**Comment by ndneighbor** [comment]
Do you have a sample repo we can use so that we can replicate this? It seems like we should have at minimum a `NIXPACKS_RUST_BIN` option or something so at least you can point the builder to right bin. 

 or... maybe you can give us a custom build command that scopes you down to using a `cargo` workspace but I am not too familiar with expected Rust project patterns. JR or Neb know much more about this than I.

**Comment by m1guelpf** [comment]
Here's an example repo that highlights the issue (I'm using [Hop](https://hop.io)): https://github.com/m1guelpf/hop-deploy-test

Just the default cargo project, modified to have two binaries

**Comment by JakeCooper** [comment]
Looks like this is fixed upstream

https://github.com/hopinc/nixpacks/pull/15

@pxseu @robjmorrissey can y'all PR this into the main branch when you have a sec? Cheers!
