### ISSUE TITLE
Not able to use JDK 11 in Scala Play Framework App

### ISSUE THREAD

**Issue by mbasilico** [railwayapp/nixpacks#793]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I want to use JDK 11 in my Scala Play App.
I am using the last version of Play Framework with JDK 11 (Play Framework 2.8.16 is not compatible with Java 19).

I tried a lot of things:

-  Puting env variables tell raiway and Nixpacks to use jdk 11

- The build log says the following:

#8 84.95 error: collision between /nix/store/sr0ncsr0f1ph3p7hn8y5gypqwrf33r8i-openjdk-11.0.15+10/include/jni.h' and /nix/store/lnqmv17pbjpyldjnk07kr0k1ngfx5gw4-openjdk-19.0.1+10/include/jni.h'

    I see that the scala provider ( https://github.com/railwayapp/nixpacks/blob/main/src/providers/scala.rs#L79 ) is different that the Java one in how It uses JDK variables but I do not know If this is a problem or not.

### To reproduce

Just use the env variable NIXPACKS_PKGS with value jdk11 in railway.
The build will fail.

### Expected behavior

Build and Run Scala project with jdk11

### Environment

I am building with railway.app

**Comment by ndneighbor** [comment]
Pinging @yzia2000 - any guidance on what we can do to add this to the provider?

**Comment by yzia2000** [comment]
Yeah we could certainly do something about this. Let me send a PR

**Comment by yzia2000** [comment]
Basically, we can make sure that the sbt package is compiled with the right jdk version
