### ISSUE TITLE
Create image at once with frotend and backend in it. 

### ISSUE THREAD

**Issue by bdelium** [railwayapp/nixpacks#823]
### Feature request

Dir structure:
```
Common-----|
            Frontend
            Backend
```
                       
Run                      
nixpacks plan Common - detect Frontend and Backend configuration for the image.
nixpacks build Common - build an image with Frontend and Backend.

**Comment by coffee-cup** [comment]
That is sort of possible currently. You could build both the front and backends during the build phase and then start them both with a process manager like pm2. However, automatically detecting that is not the intended use of Nixpacks and it is recommended that each running container only does a single thing.

If your backend serves your frontend (e.g. rails/nextjs), then this is a different story.
