### ISSUE TITLE
RFC: Support other container runtimes

### ISSUE THREAD

**Issue by aleksrutins** [railwayapp/nixpacks#83]
I specifically have in mind [Podman](https://podman.io/).

This could probably just be done as a fallback - if Docker's found, use it, else try Podman, etc.

Also, Podman has some interesting features that might be useful for Nixpacks - for instance, [Buildah](https://buildah.io/), which is a tool for building containers imperatively.

**Comment by coffee-cup** [comment]
This is a good idea. There is nothing in Nixpacks that should be Docker specific and supporting multiple container runtimes would ensure that. A first step would be to abstract the generation of the Dockerfile into a trait that could be implemented by a `DockerGenerator` or a `PodmanGenerator`.

**Comment by wyzlle** [comment]
Migrated to #121
