### ISSUE TITLE
Extremely Slow Build in K8s

### ISSUE THREAD

**Issue by type-checker** [railwayapp/nixpacks#854]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I am using nixpacks in K8s with Kaniko builder. The build speed is very slow. `nix-env -if .nixpacks/nixpkgs-293a28df6d7ff3dec1e61e37cc4ee6e6c0fb0847.nix` takes 40-50 min. to compete the process. I tried mounting prebuilt packages on `nfs` and cache it during the build but cache is not working. Looks like I am missing something.

Is there any guide available to run Nixpacks in K8s or how to cache nixpacks packages with file sharing like mounting on NFS to increase the build speed.

### Expected behavior

Fast Build

### Environment

Kubernetes, Kaniko Build Pod, NFS

**Comment by Julian-Louis** [comment]
Hello @type-checker, were you able to find a solution?
