### ISSUE TITLE
Node provider fails to detect caret-prefixed versions

### ISSUE THREAD

**Issue by half0wl** [railwayapp/nixpacks#858]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In the Node provider, the primary check for Node versions happen in [src/providers/node/mod.rs#L328](https://github.com/railwayapp/nixpacks/blob/947a417d91cd00b872b4655fc39f595090a6c2d0/src/providers/node/mod.rs#L328). The regex does not capture preceding carets (`^`) - it starts with a digit until a delimiter (`.` etc.) causing caret-prefixed `^` version strings to be ignored entirely.

When the detection above fails, it falls through to [src/providers/node/mod.rs#L334](https://github.com/railwayapp/nixpacks/blob/947a417d91cd00b872b4655fc39f595090a6c2d0/src/providers/node/mod.rs#L334) which also fails caret checking (it only checks for GTE versions i.e. `>=`).

Caret versions should be supported because they are valid (intended for bumping versions to `minor.patch` versions (`^18` => `18.$latestMinor.$latestPatch`) and widely-used.

Relevant block of code:

https://github.com/railwayapp/nixpacks/blob/947a417d91cd00b872b4655fc39f595090a6c2d0/src/providers/node/mod.rs#L315-L339

---

As a side note, it looks like we're returning the default specified Node version (v16, as a const in [src/providers/node/mod.rs#L25](https://github.com/railwayapp/nixpacks/blob/947a417d91cd00b872b4655fc39f595090a6c2d0/src/providers/node/mod.rs#L25)) regardless of whatever `NODE_VERSION` is provided (in env, `package.json`, etc.) This looks like it should be returning the `node_version` from [src/providers/node/mod.rs#L317-L320](https://github.com/railwayapp/nixpacks/blob/947a417d91cd00b872b4655fc39f595090a6c2d0/src/providers/node/mod.rs#L317-L320) (where a `match` is performed on provided Node version, defaulting to the v16 const) instead of the default version const itselt, but I suppose that's intended because it may result in unintended behaviour when a non-supported version string is provided.

### Environment

n/a

**Comment by Miloas** [comment]
@half0wl that means if my node version constrait like `^18.1.1`, it may install a `DEFAULT_NODE_PKG_NAME` node version, right?
