### ISSUE TITLE
Python Provider: Phases after install do not have access to Python

### ISSUE THREAD

**Issue by coffee-cup** [railwayapp/nixpacks#872]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Python Phases after the install phase do not have access to Python or any of the installed pip packages.

I beleive the issue because the `.profile` file update is happening at the end of the build (introduced here https://github.com/railwayapp/nixpacks/pull/842).

Which version 1.6.0 of Nixpacks, running `which python` in the release phase points to the global python installation, not the python inside the virtual environment.

![screenshot-2023-05-05-16 58 50](https://user-images.githubusercontent.com/3044853/236567856-2cea95ee-5e4e-4dea-9fdc-1712249771ef.png)

### To reproduce

Create any phase after the install phase and try to access Python. This is often encountered when trying to run a `release` phase from a Procfile

### Expected behavior

All phases after the install phase have access to Python and all installed packages

### Environment

Nixpacks 1.6.0+

---

Some initial investigation:

Setting the environment inside the Dockerfile (`ENV PATH="/opt/venv/bin:$PATH"`) does work. However, when the subsequent commands run, the Nix profile environment variables are prefixed. I am not quite sure where these are coming from.

![screenshot-2023-05-05-17 15 39](https://user-images.githubusercontent.com/3044853/236570124-45946b32-5c1f-462e-bb3f-0a247e287e76.png)

**Comment by Miloas** [comment]
@coffee-cup it seems this Nix profile env var are prefixed in base img

Log after `FROM ghcr.io/railwayapp/nixpacks:ubuntu-168177616`:
<img width="1738" alt="Screenshot 2023-05-11 at 02 12 54" src="https://github.com/railwayapp/nixpacks/assets/11530682/9bab2470-fc56-4cf1-b9a5-cdf26c47d5c3">


and I tried on latest master branch, cant reproduce this bug 🤔️
<img width="1296" alt="Screenshot 2023-05-11 at 02 18 47" src="https://github.com/railwayapp/nixpacks/assets/11530682/c4d617ba-58da-42f1-b2ff-51a8ed85a921">
