### ISSUE TITLE
output docker image is heavy

### ISSUE THREAD

**Issue by rawnly** [railwayapp/nixpacks#893]
Hey I'm trying to integrate nixpacks in our deployment process. But the output seem to be unbelievable big (first item in the image) compared to the current Dockerfile output (second item in the image). 

Some context:
- It's a pnpm monorepo using turborepo.
- I ran `nixpacks plan .`  and provided some adjustments for env vars.
- Running `nixpacks build .` builds correctly but the output size seem to be very big. 

This also happens with a fresh nextjs app initialized via `pnpm create next-app` (~2.5gb)

![image](https://github.com/railwayapp/nixpacks/assets/16429579/1de39d67-6db9-4d55-bc07-df2d3eabfefa)

Am I doing something wrong?

**Comment by coffee-cup** [comment]
I think the node_modules are being included in the build? Can you try removing all files that are ignored and build again.

**Comment by coffee-cup** [comment]
Closing for staleness. The built image should definitely not be 10+ GB and I suspect some non-intended files/directories are being included. Please re-open if this is not the case or if you have an example repo to share where building with nixpacks creates and very large image.
