### ISSUE TITLE
Gradle 8 support

### ISSUE THREAD

**Issue by wooodenleg** [railwayapp/nixpacks#921]
### Feature request

Hello, could you please add support for gradle 8? I am getting following error

```
Nixpacks build failed
﻿ 
﻿Error: Unsupported Gradle version: 8
```

### Motivation

I have Android + Backend mono repo and I cannot upgrade to new gradle versions because my backend builds start failing if I do

**Comment by iamkhs** [comment]
yeah, I am also facing this issue! on my spring boot backend

**Comment by prakashelango** [comment]
Having same issue.
