### ISSUE TITLE
can't install using brew on arm MacBook - sha256 mismatch

### ISSUE THREAD

**Issue by anuaimi** [railwayapp/nixpacks#923]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

when I try and install using brew, it downloads the package but reports a sha256 mismatch with the file

### To reproduce

```
 arch -arm64 brew install railwayapp/tap/nixpacks
==> Fetching railwayapp/tap/nixpacks
==> Downloading https://github.com/railwayapp/nixpacks/releases/tag/v1.9.2/download/nixpacks-v1.9.2-x86_64-apple-darwin.tar.gz
#=#=- #     #
Error: nixpacks: SHA256 mismatch
Expected: 20e71028d663dcb5ccc06fd962c49ce3918ce3a96c1edc503d534bb8f2752490
  Actual: 00d83feb2fb199608527c92ce3b4c65f827acc12243242ae4a631856ad0723ef
    File: /Users/athirnuaimi/Library/Caches/Homebrew/downloads/9af40af06cd6f0d70a35878611207e55dc05913bd900627f78ee70d49a5427a2--nixpacks-v1.9.2-x86_64-apple-darwin.tar.gz
To retry an incomplete download, remove the file above.
```

### Expected behavior

sha of downloaded file matches expected sha

### Environment

MacBook Pro Air (M2) with Ventura

**Comment by hkarthik** [comment]
Same issue on OSX Darwin Mac
![image](https://github.com/railwayapp/nixpacks/assets/131488/6f0d30d7-1209-497e-a59b-000514b6b5d7)

**Comment by mcansh** [comment]
still an issue with 1.10.0
![image](https://github.com/railwayapp/nixpacks/assets/11698668/a8b25206-f03d-4702-a7b3-2d5e72cfde06)

**Comment by mhessdev** [comment]
Looks like the brew formula changed. https://formulae.brew.sh/formula/nixpacks seems to be the new one,

`brew install nixpacks`
