### ISSUE TITLE
Use regular caching on CI

### ISSUE THREAD

**Issue by Milo123459** [railwayapp/nixpacks#94]
https://github.com/railwayapp/nixpacks/blob/eb1c51c1161dfdf0edb881302036125a8dc99393/.github/workflows/ci.yml#L46

Is there any reason we are using this instead of just @actions/cache or some Rust configured one? Or is this doing something else?

**Comment by aleksrutins** [comment]
I think that that's specifically for the `docker run` tests, to cache built Docker layers between runs. I'm not sure that @actions/cache can do that, and if it can, it's probably a good bit more complicated.

**Comment by coffee-cup** [comment]
Yes @aleksrutins is correct. It simply just caches the Docker layers and does not have anything to do with the Rust cache.

However, it has been causing some issues lately so I might remove it.
