### ISSUE TITLE
Nginx config template throws error on deployment

### ISSUE THREAD

**Issue by jakobpack** [railwayapp/nixpacks#968]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When using the template config file (`src/providers/php/nginx.template.conf`) in my project as `nginx.conf`, I get the error:

`nginx: [emerg] directive "include" is not terminated by ";" in /app/nginx.conf:11`

when deploying my app.

Is this a problem with my Railway configuration?

### To reproduce

1. Copy file contents of `src/providers/php/nginx.template.conf`
2. Create new file `nginx.conf` on project root directory with copied content
3. Deploy to Railway

### Environment

Nixpack ?.? (don't know how to find out)

**Comment by brody192** [comment]
You used the `nginx.template.conf` file so the file name you use in your project should also be `nginx.template.conf` You are likely just missing a `;` at the end of line 11.
This is not an issue with nixpacks, and if you'd like more help please open a #Help thread in the [Railway discord server](https://discord.gg/railway)

**Comment by jakobpack** [comment]
In the [documentation](https://nixpacks.com/docs/providers/php) it states that `nginx.config` is accepted. But renaming the file to `nginx.template.conf` fixed the issue.

**Comment by brody192** [comment]
correct both files are accepted, but they are differences between them, for example the template file is passed through perl to replace the PORT variable with railways auto generated PORT

**Comment by jakobpack** [comment]
Gotcha, thank you for your help.
