### ISSUE TITLE
Glibc 2.36 error

### ISSUE THREAD

**Issue by KastanDay** [railwayapp/nixpacks#977]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Fails to install any `apt-get` packages on NIXPACKS v1.16.0, works on v1.15.0

```
/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.36' not found (required by /nix/store/xpxln7rqi3pq4m0xpnawhxb2gs0mn1s0-gcc-12.3.0-lib/lib/libstdc++.so.6)
```

Larger error from Railway Build logs:
```
#9 [stage-0 5/9] RUN apt-get update && apt-get install -y --no-install-recommends ffmpeg


#9 0.849 apt-get: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.36' not found (required by /nix/store/xpxln7rqi3pq4m0xpnawhxb2gs0mn1s0-gcc-12.3.0-lib/lib/libstdc++.so.6)


#9 ERROR: process "/bin/bash -ol pipefail -c apt-get update && apt-get install -y --no-install-recommends ffmpeg" did not complete successfully: exit code: 1
```

### Environment

On Railway, deploying a Flask app.

**Comment by coffee-cup** [comment]
Is this just a standard flask app? Is there anything else being installed? Can you please share a minimal repo where it can be reproduced

**Comment by KastanDay** [comment]
* Yes, it's just a standard Flask app. Nothing fancy at all. Originally cloned from the official Railway template.
* No, there is nothing else being installed (no other apt-get installs). After the single apt-get install, we do a `pip install -r requirements.txt`, but that's unrelated to this bug.
* I'm too lazy to share a minimal repo, but here's a minimal `railway.json`. And here's [my repo where it was failing](https://github.com/UIUC-Chatbot/ai-ta-backend).

Note `v1.15.0` works, and `v1.16.0` fails with the above error. The particular apt-get install does does not appear to matter, all the packages I tried (`build-essential`, `ffmpeg`, etc.) all fail with the same error.
```json
{
  "$schema": "https://railway.app/railway.schema.json",
  "build": {
    "builder": "NIXPACKS",
    "nixpacksVersion": "1.16.0", 
    "nixpacksPlan": {
      "phases": {
        "myPhase": {
          "name": "ffmpeg (removed: libcrypt1, started to break)",
          "aptPkgs": [
            "ffmpeg",
          ]
        }
      }
    }
  },
  "deploy": {
    "numReplicas": 1,
    "restartPolicyType": "ON_FAILURE",
    "restartPolicyMaxRetries": 1
  }
}
```

**Comment by Skowt** [comment]
I'm still hitting this issue with the latest nixpack version on Railway:

Here's all the logs that mention ffmpeg during build:
```
║ setup      │ python39, postgresql, pipenv, gcc, ffmpeg                       ║
#9 [stage-0  5/11] RUN sudo apt-get update && sudo apt-get install -y --no-install-recommends ffmpeg
#9 6.888   ffmpeg-doc libasound2-plugins alsa-utils libcuda1 libnvcuvid1
#9 7.282   ffmpeg fontconfig fontconfig-config fonts-dejavu-core libaom3 libapparmor1
#9 33.08 Get:182 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 ffmpeg amd64 7:4.4.2-0ubuntu0.22.04.1 [1696 kB]
#9 38.75 Selecting previously unselected package ffmpeg.
#9 38.76 Preparing to unpack .../181-ffmpeg_7%3a4.4.2-0ubuntu0.22.04.1_amd64.deb ...
#9 38.76 Unpacking ffmpeg (7:4.4.2-0ubuntu0.22.04.1) ...
#9 42.54 Setting up ffmpeg (7:4.4.2-0ubuntu0.22.04.1) ...
````

Then when ffmpeg gets called it errors out:
```
Output from ffmpeg/avlib:

ffmpeg: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.36' not found (required by /nix/store/xpxln7rqi3pq4m0xpnawhxb2gs0mn1s0-gcc-12.3.0-lib/lib/libstdc++.so.6)
```

**Comment by pfbyjy** [comment]
ran into this issue trying to install libreoffice as an aptPkg. The workaround was to install it as a nix package

**Comment by a0m0rajab** [comment]
ran into the same issue when I used coolify

**Comment by coffee-cup** [comment]
> ran into the same issue when I used coolify

What packages were you trying to install? This can happen if the packages expect an older version of glibc. The issues from 2023 have been fixed and were related to Nixpacks using an older version of Python.

**Comment by a0m0rajab** [comment]
@coffee-cup I am not sure about that since Coolify automate the generation of nixpacks.toml file, I got over the issue when I switched to Docker with coolify.
