### ISSUE TITLE
Force nixpack. to use latest version of Bun?

### ISSUE THREAD

**Issue by MariuzM** [railwayapp/nixpacks#999]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

How can i force to use latest version of Bun?

### To reproduce

Install any bun app on railway deploys with old version

### Environment

Railway

**Comment by brody192** [comment]
please open a #help thread in our discord server [discord.gg/railway](https://discord.gg/railway)

**Comment by MariuzM** [comment]
@brody192 sorry but dont understand why needs to be via discord + go thru the process of verifying account?

**Comment by brody192** [comment]
these are the github issues for nixpacks, however, your question does not pertain to an issue, please open a #help thread instead

**Comment by MariuzM** [comment]
Depends on your definition of an issue where new version of Bun is fixing some issues i had with old. I'm only asking to have some sort of control to overide Nixpacks old version of Bun.

**Comment by coffee-cup** [comment]
You can change the version of Bun that gets installed but setting the `nixpkgsArchive` value in `nixpacks.toml`. For example, setting it to `"fce2579c3159f1ce4ea7c70cfd4f4446733d0fc2"` will use version 1.0.6 found [here](https://github.com/NixOS/nixpkgs/commit/fce2579c3159f1ce4ea7c70cfd4f4446733d0fc2)
